### ISSUE TITLE
Tombstone not spawning sometimes, all items gone 1.12.2 

### ISSUE THREAD

**Issue by Deathawaits4** [Corail31/tombstone_lite#102]
For some reason the tombstone doesnt spawn sometimes. I lost all my items twice now because sometimes when i die no tombstone gets spawned and i dont get a key. there is also no message in the chat as to where i died. I am using the newest forge version for MC 1.12.2. Also Commands dont work /TBRecovery only shows unknown command.

okay so apparently it needs to be in non capital letters, but how does the command work /tbrecovery does nothing and shows no message in the chat. I dont know if i am doing it right nor wrong. I have backups enabled but how do i actually use the backup?

**Comment by Corail31** [comment]
Hi Deathawaits4,
You should first test if grave spawns correctly when tombstone is alone (as there's no reason to have no grave except if you have no drop)
Then, when this check is ok, you can try to find the culprit in your others mods : some of them choose to handle the death sometimes, so there's no grave because the drops were handled before.
About, the command, there're in lowercase as you notice... and you can use tabulation like any command to get the other parameters, or the tombstone page on CurseForge, the syntax is on it.
NB : the command also shows the syntax, but you need to find the mod preventing the grave to appear.

**Comment by Corail31** [comment]
@Deathawaits4 what about your trouble?
