### ISSUE TITLE
Idea: Tomb Armor

### ISSUE THREAD

**Issue by Thunder-Nova** [Corail31/tombstone_lite#114]
This is mostly an Idea, more then a suggestion so no need to keep this, unless you like it enough to add it.

Tomb Armor could be an armor that will follow the player after death. (acts like soulbound, but without the enchant)

The armor is weaker then leather, and durability better then iron. But can get stronger in 3 different ways.

It will consume the experience as the player revives to get stronger, but can also get stronger by using the scroll of knowledge with the armor in an anvil but less effective then dying with the armor on. (Example: Death will consume exp by 100%, but using the scroll of knowledge method will be 75% effective.) The reason I made it this way is that if players wants to save up on experience for other things so a risk risk situation.

To repair the armor, player can use the grave's dust in the off-hand while the main hand is empty (this will cause Nausea, so not the best when in combat).

Enchanting the armor can go up to 10 for certain enchantments and can combine different enchantments, but at the cost of strength of the armor to apply. So no early enchant abuse.
Example: Resistance 10 Fire resistance 6 and Unbreaking 4

To apply these enchantments use an enchanting book on a grave the book will float (ok, just though of Pennywise when typing that), then use the armor on the grave from the off-hand with the main hand empty. This will cost a soul from the grave.

And the last way to make the armor stronger... bury it, well you need 4 graves one per armor, this method is extremely slow (10 xp per cycle), but will eventually make the armor stronger then diamonds. Armor in off-hand and right clicking an empty grave with a shovel in main hand. To retrieve the armor right click the grave with shovel. This will also prevent the grave to get a soul.

**Comment by Corail31** [comment]
Hi Thunder-Nova, and thanks for your time to write this suggestion.
Tombstone needs to stay adequate to any pack adding it, mainly by configuring it, they are not all RPG medieval fantasy, some are skyblock.
For the future of Tombstone, i don't think there'll be new items except decorations to make a good looking cemetary, and more ways to configure the mod (like a config to fully disable any content related to teleportation).
Lots of mods are adding their own weapons/armors (tinker construct adding a modular system to create them) but in code, for me, they're all the same (with their limitations to scale them, knowing some mods scale the mobs) and even if some mods are adding them with a long process of creation, they are often unbalanced, or useless/inadapted to the current pack.
If i would add armors/dress, it would be because an artist would makes the models in an aesthetic way (no power).

**Comment by Thunder-Nova** [comment]
Point taken, the decorative I have in mind is mostly "Grim Reaper cloak and scythe", "gravekeeper gear", and a "death knight" set. Though I was thinking of a black armor that will look like a dark soul sand more and more as the wearer dies.

This suggestion is mainly though that every time when I die in most modpacks and see my experience still with me. And thinking what could make a good balancing system for such experience grinding.

The idea of a leveling armor pop in mind, but with a risk. So been building up to this.
