### ISSUE TITLE
Incompatibility with Oculus 1.4.3+ [1.18.2]

### ISSUE THREAD

**Issue by 5stigma** [Corail31/tombstone_lite#115]
### Minecraft Version

1.18.2

### Forge Version

40.1.84

### Corail Tombstone Version

tombstone-7.5.8-1.18.2

### What happened?

only enable shaders...
Crash.

If you updated and had the shaders on, it probably crashes on the startup screen. you can disable them in oculus config and it will start as normal.

[crash-2022-11-29_19.52.40-client.txt](https://github.com/Corail31/tombstone_lite/files/10118727/crash-2022-11-29_19.52.40-client.txt)

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Other relevant mods

Oculus mod

### Log Link

https://github.com/Corail31/tombstone_lite/files/10118727/crash-2022-11-29_19.52.40-client.txt

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
@5stigma Hello, can you test first with Oculus 1.2.5a ? (the version that the compatibility test has been done)
Also, reduces your mod list to Rubidium, Oculus and Corail Tombstone for the test.
Can you also make sure that Oculus doesn't crash without Corail Tombstone ?
NB: errors with mixin are hardly catchable by Forge.

**Comment by 5stigma** [comment]
yes, with Oculus-1.2.5a it works fine, only report for helping those that have the same issue.

and, yes, tested only with rubidium, oculus and, corail tombstone

**Comment by Corail31** [comment]
@5stigma the only visible changes on oculus github 1.18.2 are from augustus... and i only use a virtual class (pseudo annotation) so i doubt it could be from my mod.
I'm going to test ~~if you answer to my last question ;)~~

**Comment by Corail31** [comment]
@5stigma Oculus is normally incompatible with Corail Tombstone (except 1.16.5) because the transparent particles are not displayed, which prevents understanding the gameplay.
A compatibility has been added for version 1.2.5a in order to provide a solution that is no longer valid with version 1.4.3.
So, it's up to you to stay on version 1.2.5a as i won't probably change this (~TransformPatcher.class).
https://github.com/Asek3/Oculus/issues/229
I sent them a message to explain the problem because i want to keep at least the only version really working with their mod.
Edit: If it's still not clear, **compatibility is required to use 'Oculus' with 'Corail Tombstone' if shaders are enabled**, so there's no point trying to use 1.4.3. The real solution is to wake up the other modder. Oculus is not specially incompatible with my mod, it's incompatible with any mod wanting to use a shader with Forge stuff. Mojang has tended to prevent 'transparency' (~low alpha, not 'translucent') since several versions, the reason why i use a shader since 1.17 and i have limited knowledge in GLSL (the best fog particle being in 1.12.2).
Ideally, Assek could rename the NewShaderTest class and the problem would be solved and i would keep compat with 1.2.5a.

**Comment by barnaclebytes** [comment]
> @5stigma Oculus is normally incompatible with Corail Tombstone (except 1.16.5) because the transparent particles are not displayed, which prevents understanding the gameplay. A compatibility has been added for version 1.2.5a in order to provide a solution that is no longer valid with version 1.4.3. So, it's up to you to stay on version 1.2.5a as i won't probably change this (~TransformPatcher.class). [Asek3/Oculus#229](https://github.com/Asek3/Oculus/issues/229) Edit: i sent them a message to explain the problem because i want to keep at least the only version really working with their mod.

When you say incompatible, are you saying that the expected behavior for tombstone in 1.18.x combined with oculus versions above 1.2.5a is catastrophic failure? I ask because I have been using oculus for the past year or so in 1.18.x with your mod and it has been fine. my problems began when I upgraded from 7.4.9 to 7.6.0 trying 7.6.1 today. 

The latest version I am able to run of tombstone is 7.5.6 with oculus 1.4.3 and 1.4.3a. Since the October 2022 version tombstone works with the newest oculus, to me, this suggests that the problem could be on your end. 

the following line in my logs pointed me to tombstone as a place to start.
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on tombstone.mixins.json:NewShaderTestsMixin->@Inject::methodMakeShader

Thanks!

**Comment by barnaclebytes** [comment]
> @5stigma Oculus is normally incompatible with Corail Tombstone (except 1.16.5) because the transparent particles are not displayed, which prevents understanding the gameplay. A compatibility has been added for version 1.2.5a in order to provide a solution that is no longer valid with version 1.4.3. So, it's up to you to stay on version 1.2.5a as i won't probably change this (~TransformPatcher.class). [Asek3/Oculus#229](https://github.com/Asek3/Oculus/issues/229) Edit: i sent them a message to explain the problem because i want to keep at least the only version really working with their mod.

When you say incompatible, are you saying that the expected behavior for tombstone in 1.18.x combined with oculus versions above 1.2.5a is catastrophic failure? I ask because I have been using oculus for the past year or so in 1.18.x with your mod and it has been fine. my problems began when I upgraded from 7.4.9 to 7.6.0 trying 7.6.1 today.

The latest version I am able to run of tombstone is 7.5.6 with oculus 1.4.3 and 1.4.3a. Since the October 2022 version of tombstone works with the newest oculus, to me, this suggests that the problem could be on your end.

the following line in my logs pointed me to tombstone as a place to start.
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on tombstone.mixins.json:NewShaderTestsMixin->@Inject::methodMakeShader

Thanks!

**Comment by Den4enko** [comment]
I have just disabled "NewShaderTestsMixin" in a jar file, and everything works fine.
