### ISSUE TITLE
Can't disable tomb raiding

### ISSUE THREAD

**Issue by ricchix** [Corail31/tombstone_lite#12]
### Minecraft Version

1.16.5

### Forge Version

36.2.0

### Corail Tombstone Version

6.5.1

### What happened?

Tried to disable tomb raiding for a server but other players can open other players tombs.

### Gametype

Dedicated Server

### Tested with only Corail Tombstone

- [x] Yes

### Relevant mods

Corail Tombstone

**Comment by Corail31** [comment]
@ricchix You didn't check if you tested it with only Corail Tombstone, so your issue is invalid if you don't make this test.
You're probably misunderstanding what Tomb Raider is doing (it's disabled by default and only concerns bad alignment players) and the fact to have access to a grave or not (depending on the configuration of the server).
When you have a grave, you have a message so it's perhaps better to start by reading it (if locked for an amount of minutes or unlocked). This is based on the player's death configs (decay_time, being the time to be accessible to anyone).

**Comment by ricchix** [comment]
I will try in a moment only with this mod.

**Comment by ricchix** [comment]
I tried it in a server with only this mod, the other player couldn't open my grave.
Then I deleted the other servers config files and tried it. It worked too, but the thing is that I didn't change anything related to grave opening behaviour, I think I only changed how many knowledge points you get and the percentage to get the enchanted key.
Thanks for your attention, I will keep testing to see what's the problem.

**Comment by Corail31** [comment]
I can provide you some possible reasons but you may think to read the logs because the [locked]/[locked x min]/[unlocked] message can give you an idea how was set your config: 
- the config player_grave_access is set to false
- the config decay_time was to a value different of -1 (-1 = disabled)
- the server property pvp is true (if a player kills you, the grave is accessible to anyone)

Edit: with your explanation (related to enchanted key config), i'm nearly sure you changed the player_grave_access (the description of this config is not accurated to what it's doing)

**Comment by ricchix** [comment]
I checked yesterday's logs and the grave was unlocked but the other player couldn't open it, I tried again today and the other player could open it, and it was still unlocked. I don't know why this is happening, pvp is enabled but allow_tomb_raiding is set to false. The config files are the default ones but one thing, I changed the percentage to the enchanted key. What else should I change to have pvp enabled while other players don't have the possibility to open other players tombs?

**Comment by Corail31** [comment]
There's an additional particularity: for 10 min after the server started, it prevents to open graves if you're not the owner and have no key.
But again the message that you receive is different so except if you really read theses messages in game, i can't help you more.

**Comment by ricchix** [comment]
I checked the message and when a mob that is not a player kills me it says locked, but when a player kills me it is unlocked. I have no idea how to make it so it's locked no matter what kills a player. I would like to know if you know a way to keep pvp enabled and the tombs to always be locked to other players.
Again, thanks for your attention.

**Comment by Corail31** [comment]
ah it means that you have the pvp enabled on your server (edit the server.properties file, there's an option pvp in)
NB: actually if pvp is enabled, it applies this rule, older versions of tombstone use a config pvp instead. I changed the description of the configs that could not be accurate for future versions. Out of curiosity, why to enable pvp if it's to disable to steal them as i could re-add this config ?

**Comment by ricchix** [comment]
If pvp wasn't enabled players could not hit each other (I think), having a server with friends and not being able to hit or kill others will not be as fun. But by being able to open other players grave you could misclick and take all the items from the other player, not only that, being able to steal someones WHOLE inventory is not that fun for any player, in my case, we have many mods so there's many items, it's really hard to remember everything we had to tell the other player to return the items. Basically it's to keep fun. Not being able to hit, kill, or troll a lil bit wouldn't that fun playing with friends, but nobody wants to deal with stealing, misclicking, etc.. Everybody sets their inventory how they want, and I wanted to keep it that way.

Extra question: the older versions of this mod that have the pvp file are compatible with newer versions of forge or minecraft?

**Comment by Corail31** [comment]
The config pvp has been removed in 6.4.7 (the actual recommanded version), so 6.4.6 would be fine for you.
I'll re-add that option (probably better renamed), and yes, all versions are always compatible (forge doesn't make breaking changes in 1.16.5)

**Comment by ricchix** [comment]
Ok, thanks a lot. I'll be waiting for that :)

**Comment by Corail31** [comment]
@ricchix 6.5.2 ;)
