### ISSUE TITLE
Trying to recover items due to being unable to locate grave

### ISSUE THREAD

**Issue by Jackchessell1** [Corail31/tombstone_lite#121]
### Minecraft Version

1.19.2

### Forge Version

43.1.55

### Corail Tombstone Version

8.2.1

### What happened?

I encountered an issue where I fell into the void in the end and the game did something quite peculiar the game spawned me back with a grave key as it normally does however when I  travelled to the end for some reason when I got close to my death waypoint my key disappeared and when I arrived at the waypoint there was no grave my friend who runs the server and I have tried several ways to fix this such as overwriting grave contents using previous saves, using the recover player command, editing inventory files, and we just can't seem to figure out how to restore my items we're truly at a lose and anything remotely helpful suggestions would be tremendously appreciated 

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs rarely

### Other relevant mods

Sophisticated backpacks

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
If you know that the problem is coming from Sophisticated Backpacks, why don't you report to them ?
The command /tbrecovery has no reason to not work... you just need to restore it enougly fast before others saves are done (there's a limit amount of saves by player).
Again, you're not reporting an issue but asking for informations and it's not the place, the list of commands are displayed on the Corail Tombstone's page on CurseForge.
The command /tbrecovery is to restore players from a save. The command /tbrestoreinventory is to 'click at range' an existing grave. If your key disappears, it means that the key detected the grave was no more present (or never was).
You have logs that can help you (and me) when you get an error when dying.
The only thing that comes to my mind is the incompatibility with Sophisticated Backpacks and "lollipops" but was solved on both sides one month ago (so you just need to be updated on both mods).
