### ISSUE TITLE
Corail tombstone and Dragon Survival Mod Crash after claiming inventory if there is any Claw tool.

### ISSUE THREAD

**Issue by 5stigma** [Corail31/tombstone_lite#122]
### Minecraft Version

1.18.2

### Forge Version

40.1.84

### Corail Tombstone Version

tombstone-7.5.8-1.18.2

### What happened?

When you die as a dragon with any tool compatible with Claw slot, and try to claim your grave the game crashes instantly.

a temporary solution would be: disable Auto-equipped in client-config for Corail tombstone

### Gametype

Singleplayer, Dedicated Server

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Other relevant mods

Dragon Survival Mod and GeckoLib Mod

### Log Link

https://github.com/DragonSurvivalTeam/DragonSurvival/files/10299202/crash-2022-12-24_15.44.19-server.txt

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by 5stigma** [comment]
[Link](https://github.com/DragonSurvivalTeam/DragonSurvival/issues/241)

**Comment by Corail31** [comment]
@5stigma You probably can use an old version of DragonSurvival for the "autoequip" compatibility, their api being quiet limited... leading indirectly to this because there is no guarantee that the code does not change on their side, so the comment of the other modder is slightly laughable. I'll look to adapt my compat (or to remove it).
NB: the initial compatibility has been tested with dragonsurvival-1.18.2-0.11.4.

**Comment by BlackAures1** [comment]
I don't do code and don't know the details. I remember that Horeak has fixed it before, but apparently it doesn't work again. Sorry for the "slightly laughable comment".

**Comment by Corail31** [comment]
@BlackAures1 With this kind of announcement, i'll simply remove the compat...
"Our main programmer Horeak has left the project and all the code will now do the owner of the mod - Black Aures. I have always been a person who deals with the community and all the graphical part of the mod, so do not expect from me some incredible knowledge of the code. I'm an artist, but I will do my best to keep the project alive."

**Comment by BlackAures1** [comment]
Is this compatibility promised by Horeak or what does it have to do with him?

**Comment by Corail31** [comment]
What is the point of wanting to stop being the coder of a mod except if there's conflict in the team? The time invested in a mod can be colossal and it doesn't change what has already been accomplished.
In any case, I prefer to let you solve your team problems, and I will remove compatibility for new versions of your mod (by preventing the crash).
related: #56 #59

**Comment by BlackAures1** [comment]
1. Why do you think we have some kind of conflict? Horeak is just now working officially and doesn't have time to do Dragon Survival. He told me he wanted to leave the project and that's it. I'm still in contact with him. There's no drama here and I don't understand why you're making these stupid insinuations. This project has always belonged only to me, and programmers came and went for personal reasons all time.

2. No one asked you to solve non-existent problems of our team. I just came to find out what problems you have in the code with my mod and how I can help you, but instead got some accusations. So say "I do not want to do compatibility with your mod". That's it. I will write that with your mod crashes and will advise everyone to use another mod for graves. No need to throw tantrums and draw conclusions about people you don't know.

**Comment by Corail31** [comment]
1. "Better use this mod - xx It doesn't crash ^^"
2. "I don't do code and don't know the details. I remember that Horeak has fixed it before, but apparently it doesn't work again. Sorry for the "slightly laughable comment"."
=> without your coder, i have no point to add a compatibility with no guarantee about the code (due to no api) knowing your last update was already the capability methods being changed (and the point of capability is to be useable by others mods).

Edit: The crash is solved and was the issue so, please don't spread rumors. The only thing that is changed is about 'auto-equip' no more supported in newer versions of that mod, there's a log when it's disabled - the first time a grave is recovered (there's no api in that mod about their "sub inventory" and i don't think others mods make compats).
I got a similar problem when "Aether" mod inventory was changed in 1.12.2.
