### ISSUE TITLE
Scroll of True Sight Effect Description

### ISSUE THREAD

**Issue by MC-Valdreth** [Corail31/tombstone_lite#125]
### Minecraft Version

1.18.2

### Forge Version

40.1.92

### Corail Tombstone Version

tombstone-7.5.8-1.18.2

### What happened?

Both the Enchanted Scroll of True Sight & the Ancient Scroll of True Sight are missing the word "see" in the effects description.

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hi, thank you for reporting this translation issue. If that's the only problem in the scroll descriptions, it's already surprising since I did the translation ^^
"Lets you X in the dark, in the fog and under ~~the~~ water"
For anyone on this issue, please feel free to suggest edits regarding the scroll descriptions, this is not my native language.
NB: translations for scrolls (even vanilla) are provided in waiting "Potion description" mod to update to upper versions.
