### ISSUE TITLE
Key duplication

### ISSUE THREAD

**Issue by GuerreroCraft61** [Corail31/tombstone_lite#126]
https://youtu.be/sL0QFf8NDSg

    # The chance that a player receives an already enchanted Grave's Key on death
    # Min: -1
    # Max: 100
    I:chanceEnchantedGraveKey=100

    # Whether to require a Grave's Key to access graves
    B:playerGraveAccess=true

All config: https://gist.github.com/GuerreroCraft61/658eafc418a3751be98dcf95a0e44754

**Comment by Corail31** [comment]
It's not a bug it's intended, a key only works for a grave, and if it's enchanted it's because you don't use the normal gameplay and a more cheated option.
The key automatically disappears when it detects the grave is no more there, but as i'm wise the check if not so often, except if the latest release where i added a special check when you have the key in hand and is near the grave.

**Comment by GuerreroCraft61** [comment]
But when you have full inventory, it gives you the key before you die (I have the PlayerRevive mod, I don't know if it affects) and drops it, so when you return with the enchanted key, you take the old and the new one and if the mob op (Infernal Mobs) kills you again, makes your inventory fill with keys.

**Comment by Corail31** [comment]
What happen with player revive, is related to this mod.
If you have a key you have already dropped your stuff, and a grave has been created, if your player inventory is full, it's because this mod transfered all your inventory in the player body, so in this case, why do you have a grave?

**Comment by Corail31** [comment]
@GuerreroCraft61 Your second question could be followed now here, as it's a different subject.
https://github.com/Corail31/tombstone_lite/issues/127
