### ISSUE TITLE
Ankh Cooldown

### ISSUE THREAD

**Issue by SkotKeller** [Corail31/tombstone_lite#127]
### Minecraft Version

1.19.2

### Forge Version

43.1.55

### Corail Tombstone Version

8.2.2

### What happened?

The Cool Down is set to real life hours not in-game hours.
The range on CD is 1-10 and set base 3 when trying to use it again.
So least you can set to is 1 real life hour which seems to be over kill a bit considering one minecraft day is 36 mins.

### Gametype

Singleplayer, Dedicated Server

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
It's how it's set for the cooldown of the Ankh, more precisely it's 1 hour of played time.
The Ankh is a special item rarely useable (and during halloween, this cooldown is also what prevents the ghost from appearing).
It's up to players to configure the mod based on their playtime but it's limited to 1 hour because it can charm 'tameable' dragons or undeads...
Out of curiosity, what was the use "for you" to have a reduced time ? because advancements help a lot to get knowledge of death points.
