### ISSUE TITLE
Does Tombstone have problems with Shaders??

### ISSUE THREAD

**Issue by WickedS1ck** [Corail31/tombstone_lite#130]
### Minecraft Version

1.18.2

### Forge Version

40.2.0

### Corail Tombstone Version

tombstone-7.6.0-1.18.2

### What happened?

So i installed Oculus mc1.18.2-1.4.3a   ( the newer version) and add a shader pack the problem is that when i activated it the game crash and now keep crashing but for some reason when i remove it the problem is solved

[latest.log](https://github.com/Corail31/tombstone_lite/files/10477055/latest.log)

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Other relevant mods

Oculus?

### Log Link

[LOG](https://github.com/Corail31/tombstone_lite/files/10477055/latest.log)

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
@WickedS1ck Hi, can you have a look to this issue:
https://github.com/Corail31/tombstone_lite/issues/115
To explain you in simple: when shaders are enabled in oculus, tombstone particles vanish. There was a compatibility to avoid this with oculus 1.2.5a that is broken in upper versions of oculus (and i can't make a compat for both cases so i kept the compat for 1.2.5a as 1.18.2 is normally outside of the scope of supported versions).
The other solution would have been to remove the compat (with the particles not visible), so to be incompatible.
NB: Oculus has a repository not easy to read due to their source based on Iris: to give an idea, this is the change in oculus for 1.4.3: Showing 600 changed files with 81,414 additions and 1,971 deletions in one unique commit.

**Comment by WickedS1ck** [comment]
hmm i see and what version of tombstone have the compat?, or any version works for oculus 1.2.5?

**Comment by Corail31** [comment]
Read the "pinned" issue (all versions work with 1.2.5a since 7.5.7, except with the shaderpack 'Supplementaries' that the compat disables itself with a log and i contacted the other modder but got no answer).

**Comment by liketechnik** [comment]
Sorry, not to disturb anyone here, but I just confirmed the suggested fix on Oculus side would work.

Instead of changing the source and recompiling Oculus I (ab)used a Java Bytecode De(assmbler). If anyone's interested, I could provide the instructions for 'fixing' Oculus this way (and possibly the resulting .jar-archive, though I feel slightly uncomfortable publishing butchered versions of other people's work).
