### ISSUE TITLE
Exception caught during firing event: Trying to add tag of type 10 to list of 1

### ISSUE THREAD

**Issue by Lance5057** [Corail31/tombstone_lite#133]
### Minecraft Version

1.19.2

### Forge Version

42.2.3

### Corail Tombstone Version

8.2.4

### What happened?

Died to a drown effect from an infernal mob, entire server froze in a looping crash. Required a force kill to get the server back online.

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs rarely

### Other relevant mods

Curios, Infernal Mobs (Maybe?)

### Log Link

https://pastebin.com/6xzfegpK

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Lance5057** [comment]
[Crosspost to Curios](https://github.com/TheIllusiveC4/Curios/issues/282)

**Comment by Corail31** [comment]
Hi, you completely miss how to fill the issue template: you have to locate the mod bringing this issue or to make this happening with only Corail Tombstone. Knowing that this nbt entry has a name prefix, it could be a badly intentioned mod (and the occurrence would correspond).
That's the best I can answer you because all the codes in my mod go through helpers (to keep abstraction between minecraft versions) and i already looked about this when i got a similar report in 1.19. I don't see how that could happen.
Edit: i tested my helpers related to your log but i was not able to make a similar issue. I'll 'suppose' it's related to InfernalMobs (as the 2 reports mention it).

**Comment by Corail31** [comment]
Feel free to edit your issue. Also, this might help you:
https://github.com/Corail31/tombstone_lite/issues/79

**Comment by Corail31** [comment]
@Lance5057 Can you test with the new version of Infernal Mobs if you are still able to get a crash?
