### ISSUE TITLE
Tablet of cupidity

### ISSUE THREAD

**Issue by mattba10** [Corail31/tombstone_lite#136]
### Minecraft Version

1.19.3

### Forge Version

43.2.3

### Corail Tombstone Version

8.2.4-1.19.2

### What happened?

There is nothing on tablet of cupidity - like NO information what-so-ever
Send help

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Initially, the tablet of cupidity was based on something allowing to know where the chests were, and you had chance to spawn in front of a chest or a mob spawner. Since the mojang code changed, so actually it only leads to mob spawner ;)
So depending on your minecraft versions, it may look useless as i didn't change the behaviour to something else (it also modifies your alignment down by using this item).
