### ISSUE TITLE
Tamed mobs won't breed

### ISSUE THREAD

**Issue by DoctorMage** [Corail31/tombstone_lite#137]
### Minecraft Version

1.16.5

### Forge Version

Forge 36.2.39

### Corail Tombstone Version

6.8.8

### What happened?

Mobs that have to be tamed won't breed

Tested horses, donkeys , wolves, ~~parrots~~(parrots cannot be breed in general), cats

Feed them food used to breeds hearts will be displayed but they won't breed

seems to have occured after tombstone-6.8.3-1.16.5

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Log Link

https://gist.github.com/DoctorMage/60c56844b6fbc32d6df0db108498a1c2

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
@DoctorMage do you mean since you have updated several mods on your modpack, or do you really have a reason to think that it only happens with Corail Tombstone? (and so you tested with only the mod to confirm it)

**Comment by DoctorMage** [comment]
I've tested corail 6.8.8 purely by itself and mobs will not breed at all if
they have to be tamed by players

**Comment by DoctorMage** [comment]
Correction mobs that can be tamed once tamed will not breed

**Comment by Corail31** [comment]
@DoctorMage and when you test with 6.8.2 alone, no prob ? (i want to be sure it's not vanilla or forge as i don't play so the test with no mod would also help)
Edit: i'll take a look on Saturday but i still need the other test (these are quick tests compared to loading a modpack, and i stopped to try to recover my account from migration).

**Comment by DoctorMage** [comment]
6.8.2 exact same

they will get love hearts but won't try to breed if they are tamed

**Comment by Corail31** [comment]
Edit: i delete my comment because I did not have the same results, the 2nd time. So i need to do more tests.
From my tests, the bug seems to only affect 1.16.5 version of Tombstone. (Steps: give raw fish to 2 summoned cats until they get a collar and sitting them down, then give them fish again and let one get back up)
It looked related to one of my mixin, so i'll make an update. Thanks you for reporting this issue.
if I'm right: in 1.16.5, for animal breeding, they need to be able to attack their partner.
