### ISSUE TITLE
Sacrificial Dagger in Bloodmagic causing tombstone not to spawn.

### ISSUE THREAD

**Issue by TheFlumph** [Corail31/tombstone_lite#14]
### Minecraft Version

1.12.2

### Forge Version

Forge -1.12.2 - 14.23.5.2855

### Corail Tombstone Version

tombstone-2.9.8-1.12

### What happened?

Some important pretext would be that this is a modpack I created and am running on a server with 4 other people. I'm using Corail Tombstone in conjunction with Astral Sorcery, and Bloodmagic among other things. but for the sake of the issue thats all that matters. I had the phoenix perk under Astral Sorcery that prevents death and causes damage in a radius. However, this was overwritten by the sacrificial dagger from Blood Magic. When I died, the server console read that Tombstone recognized the phoenix affect and didn't create a tombstone nor give me a key. but I still died. and my items disappeared. I would assume that means the mod tried to spawn me a tombstone then recognized the phoenix affect and didn't. is their any command or in game affect I could use to get my items back?

### Gametype

Dedicated Server

### Happen with only Corail Tombstone

No

### Other relevant mods

Blood Magic 1.12.2, Astral Sorcery 1.12.2

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
I made a fix for this in the past and it disables itself after version 1.12.2-2.4.1-103 of bloodmagic.
Depending on your version of bloodmagic, you'll get this message in the server log:
"Enabling the patch for Blood Magic (preventing the sacrificial dagger from killing a player twice, causing them to lose their inventory), you won't see this message again if you update your Blood Magic version."
The fix is removed in upper versions of bloodmagic because they finally fixed it after years, if they broke it again since, you should report to them and mention their working version 1.12.2-2.4.1-103.
Edit: to recover your inventory, you can use /tbrecovery load_player <player> [save] (with a save before the death)
NB: 2.9.8 is not supported, update to 4.0.0 or above. As a precision, it's a bug in Blood Magic, happening because one of your mod has canceled the death event, and is not related to Corail Tombstone except the fact the loots were lost and so, no grave.

**Comment by Corail31** [comment]
https://github.com/WayofTime/BloodMagic/issues/1836
