### ISSUE TITLE
Plague Bringer enchantment corrupting data after conflict with simply swords/better combat

### ISSUE THREAD

**Issue by n0valey** [Corail31/tombstone_lite#141]
### Minecraft Version

1.19.2

### Forge Version

1.19.2-forge-43.2.0

### Corail Tombstone Version

tombstone 8.2.5-1.19.2

### What happened?

Me and my friends are currently playing on a modded minecraft server, whenever using a weapon with plague bringer on a boss (warden, apotheosis boss) the game crashes, and the specific player's playerdata corrupts. My friend did some trial and error (I originally thought it was an incompatability between apotheosis and the origins mod, due to my friend first crashing and corrupting his data by hitting an apotheosis boss while in the ground), it seems that some of the hidden effects from simply swords or better combat is conflicting with the plague bringer enchantment. It recently happened again when another player hit a boss with a simply swords iron katana with the plague bringer enchantment on it to hit a boss, and his playerdata also got corrupted. 

Also something seemingly brought upon by Plague Bringer, my friend occasionally gets launched into the air with a series of firecharges, when hitting an enemy with the sword with plague bringer on it.

It doesn't cause a "crash" that gets recorded in the logs, but I do have console info from when it happens.

Thank you!

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

Simply Swords, Better Combat, 

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hi, you don't provide any info that could help you, like a log (that would help greatly about the problem).
To my opinion, Apotheosis is a broken invasive mod and the modder has no respect for the issues related to my mod so i tend to use the same kind of respect (you can check its issues related to my mod).
I never got such report since the launch of 1.19.2, so i will recommand you to set the modids (or the mod effect) of the related mods in the config  "unhandled_harmful_effects" so they won't be used by Plague Bringer. It could also be used to locate the effect being problematic.
It would be fine to know how you set up Apotheosis for the limit of enchantment level of Plague Bringer.
If it only happens when figthing theses boss, there's a chance Apotheosis is part of the problem (and it's up to you to test with and without this mod to locate your issue, and not to try to figure out the problem based on player reports using a modpack with tons of mods).
Edit: could it be related to 2 handed weapon from Better Combat (as i saw a message on CurseForge related to it) ?
It looks you already located the mod effect in the link below. You can try to apply the effect with the command /effect too on the bosses to compare the result.
https://github.com/Sweenus/SimplySwords/issues/46

**Comment by n0valey** [comment]
That is fair! I actually found the issue lie outside of Apotheosis, it was
because of the Simply Swords gravity effect. Should I reinstall simply
swords, I will add that effect to the unhandled_harmful_effects. Thank you
for your time!

Edit Corail31: you don't need to quote my answer, it's already strange that your issue was created 3 weeks ago.

**Comment by Sweenus** [comment]
Sorry to dig up a closed ticket.

I'm currently travelling, so my capacity to investigate this is limited. The Gravity effect is WIP and not actually utilized with Simply Swords, I wouldn't be surprised if it caused issues.

Correct me if I'm wrong, but it sounds like one of these other mods are accessing the effect. If so, this is not something I had considered and is a mistake on my part. When I have the chance, I'll clean this up on my end.
