### ISSUE TITLE
Compatibility of "Combine on inventory" recipes with datapacks / kubejs?

### ISSUE THREAD

**Issue by DevDyna** [Corail31/tombstone_lite#148]
### Minecraft Version

1.19.2

### Forge Version

43.2.7

### Corail Tombstone Version

8.2.6

### What happened?

Hi , 
I just notified during making stuff that all recipes "Combine on inventory" aren't compatible to be modified / added / removed 
 another recipes of same type (example recipe to craft scrolls or dust_of_frost).
There is planned on a future version of corail tombstone to include them via a custom modular json recipe?

### Gametype

Singleplayer, Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

kubejs / *datapack*

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [x] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hi, if i understand well: you want more ease in editing the 'combination' recipes as they don't use the json system.
In Corail Tombstone, you need an item able to interact with graves to "enchant with soul" and this can done with the api.
Adding the recipe wouldn't be enough to allow the item to be enchanted. I'm going to look if i can do something about it in the future. Chance are i'll re-add the json recipes, not yet sure if it will be with a custom crafting table, and if i'll keep the 'combination'.
If you want to disable a recipe, you can disable the item in the config. For recipe ingredient, they're not a lot important, as the real ingredient is the soul (and why souls have to be rare).

**Comment by DevDyna** [comment]
ok , thank

**Comment by Corail31** [comment]
@DevDyna Out of curiosity, what were the changes you would have liked for different recipes? because for me the ingredients are not important but maybe for the players, the choice seems more obvious to them.
I could also use a tag if it's important to change the ingredient or to allow multiple items (like for the voodoo poppet or the key).

**Comment by DevDyna** [comment]
Not much to change all existent recipes but only to add a way to create custom "combine on inventory recipes" ;
for a developer of modpacks could be useful on recipes that want lock the chance of "autocraft with any autocrafter" example:
"added a recipe of 10 raw iron by combine in inventory raw iron ore and a gunpowder on a random modpack" , at "midgame" unlock a *machine* that process at same ingredients but require *a energy source* , if used a "vanilla recipe" and there is a autoworkbench available , without add others mods (gamestages , lycee) could be integrated on modpack corail tombstone as "main mods of progression" of modpack to craft only manually without way to autocraft or "classic old ways"

**Comment by Corail31** [comment]
The combinations in the inventory are not always ideal for players to know the recipe (although they can use JEI, or look at the tooltip).
They also rely on the same interaction as filling a bundle, and modders can add their own code at this place too (meaning that some items wouldn't have recipes because the interaction would have already been handled by another mod).
For my mod, this is not a trouble as i use my own items in theses recipes.
There's also the fact that tooltips display the recipes but are not ideal for displaying tons of them, and the toaster displaying messages for 'incorrect match' wouldn't be a thing for additional recipes.
It's not hard to change it as a json recipe but it would imply theses limitations.
