### ISSUE TITLE
Strange issue / behavior with the Weather2 mod textures

### ISSUE THREAD

**Issue by KarinMiku** [Corail31/tombstone_lite#151]
### Minecraft Version

1.18.2

### Forge Version

7.6.3

### Corail Tombstone Version

40.2.0

### What happened?

As the title says, when using the latest version of Corail Tombstone 7.6.3 (1.18.2) with the mod Weather, Storms & Tornadoes (Weather2) the clouds / wind / tornadoes textures look wrong while using shaders. This only seems to happen with the latest version btw, 7.6.2 has no issues.

This is how the issue looks like (7.6.3 installed / Sildur Vibrant Shaders):
![1](https://user-images.githubusercontent.com/51896289/230763777-3e49198b-56be-4b1f-a97c-9f065e528b5d.png)

And this is how it is supposed to look (7.6.2 installed / Sildur Vibrant Shaders):
![2](https://user-images.githubusercontent.com/51896289/230763786-55155663-c898-4fac-bf8c-2602900a47df.png)

Note: This was done while using the latest version of Rubidium 0.5.5 & Oculus 1.5.2

### Gametype

Singleplayer, Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

Weather, Storms & Tornadoes (Weather2)

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
I don't see the relation with the storm and weather mod, and the "particle shader" being used in Corail Tombstone.
I'll ask to Corosus to get some infos as i don't know a lot its mod.
NB: i don't accept such videos, feel free to replace with a screenshot.

Also, i'll add a resume of Iris Compat from CurseForge:
"Activating the "Optifine Shader" is an option with Oculus (being the forge version of Iris) and not the default (accessible in minecraft video settings) and requires to download some shaderpacks having each their particularities and sometimes breaking mod particles to be visible.
The Oculus changes are not yet in the 1.19.2 version, but they already changed their 1.18.2 and 1.19.4 version.
When Shaders are enabled in Oculus, my custom shader doesn't work anymore and i need to switch to the default particle shader (who doesn't render particle if the alpha is too low). This is why my previous compatibility was to edit their generated particle shader (based on the activated shaderpack) to change the line related to alpha but they changed a lot their code since and their modder doesn't answer about solutions. The new solution edits the shader in ShaderProgram (in minecraft).
So, to resume, it's only about particles being visible or not."

Additionally, the patch is applied even when Oculus is not present, so you should have the same trouble also without Oculus, if it was really on my side, i suppose. Also, if you have a problem in 7.6.3 with weather2, you already had it in 7.6.1 and before.

I appreciate you bringing this issue as i will be adding the same change in 1.19+ soon.

**Comment by KarinMiku** [comment]
Thank you for the fast reply and sorry for the videos, i didnt know about that ^^U, however, im kinda confused rn > <, i mean, do you need me to test something else? or are you saying that you might find a way to fix it in a future version?. Im glad i could help ^^

**Comment by Corail31** [comment]
@KarinMiku Thanks for adding the screenshots. If you don't have trouble with 7.6.2, it's probably the version to go on for you.
I will wait an answer of the modder of weather2 (corosus) that i contacted on CurseForge.
This is strange to see the borders of the quads on your screenshot instead of transparency.
If you really want to do something, you can test 7.6.1 with Oculus and shaders activated (and weather2) if it's the same problem. Then, you can also check 7.6.3 without Oculus to see if it's different. This could help me to understand a little better.

**Comment by KarinMiku** [comment]
With 7.6.1 im not even able to run the game ^^U (crashes at the last part of the launch-loading screen) the same happens with 7.6.0 , 7.5.8 .. etc, this is the error log:
https://pastebin.com/Gqdtk5wU

Now, i tried using 7.6.3 with and without oculus, they both look exactly the same:
-with:
![ocu](https://user-images.githubusercontent.com/51896289/230792059-30ccf7dd-b256-44f3-ae32-fab114030b12.png)
-without:
![sinocu](https://user-images.githubusercontent.com/51896289/230792066-96951b83-4450-4e20-afaf-0a7a9a981103.png)

**Comment by Corail31** [comment]
@KarinMiku 7.6.1 is compatible with Oculus 1.2.5a maximum (they changed their code since and why i changed my [compat](https://github.com/Corail31/tombstone_lite/issues/115)). 
I suppose the screenshots above are not how it should be with only weather2.
I think i can avoid the problem, i will make the test in a few days. Is there a way to easily get storms in the other mod?

**Comment by KarinMiku** [comment]
`7.6.1 is compatible with Oculus 1.2.5a maximum (they changed their code since and why i changed my compat`
oh i see, problem is, i can't use that version of oculus since the support for weather2 wasnt added until oculus 1.4.3a (u can see the changelog at the curseforge page) 

`I suppose the screenshots above are not how it should be with only weather2.`
And yea.. kinda .. i guess (?)...  thats the thing with this issue, i cant really notice a difference between using 7.6.3 and not using it (without shaders / oculus) 
This is how it looks with **only** the weather2 mod:
![2023-04-09_16 02 37](https://user-images.githubusercontent.com/51896289/230796468-bd4d5c6a-5327-4b6d-acc8-35a0270416e4.png)
i suppose there has to be a difference (?).. but the easiest way to notice is by using shaders...

And yes ofc, you can spawn those storms / tornadoes, with the following command: 
`/weather2 summon tornado_f0 `
it goes up from f0 to f4, (tornado size)

**Comment by Corail31** [comment]
I'm a bit bored because Oculus and Weather2 are both hacky mods ex [link](https://github.com/Asek3/Oculus/blob/1.18.2-dev/src/main/java/net/coderbot/iris/mixin/MixinShaderInstance.java).
Oculus prevents my custom shader to be, forcing me to adapt my code to the current version.
I'm satisfied with the current patch and if it only affects weather2 (being mainly in 1.12.2 and a little in 1.18.2), i'll prefer to choose to not be incompatible with weather 2 (as players still can use the version 7.6.2 if needed).
On the same time, i don't have the impression of weather2 to be compatible with my mod when my "magic particles" are aspirated in the storm.
The fact that Oculus seems to have specific compats with Weather2 since their version 1.4.3 (on their messy github) and their high use of mixin don't help (also the lack of communication because they could simply explain how to have custom shader working in "their" stuff or they need to specify their mod is for vanilla only).
If Corosus suggests a solution, i'll look into it. I'm sorrry for you because your report was neat.
I'll disable the compatibility when weather2 is present and Optifine shaders are enabled as my 1.18.2- versions won't get updates in the future (it's not a real solution but the storm will appear correctly but not my transparent particles).
You can contact me on CurseForge if you want a version to test the changes.

**Comment by KarinMiku** [comment]
So if i understand correctly, because of the way oculus and weather2 work, the only way to make it compatible is to make the transparent corail tumbstone particles look wrong if weather2 + shaders are present? if so, thats a shame :c however, i understand that it is quite hard to find a solution when your mod isn't the only one implicated and there is a lack of communication on behalf of the other modders. To be honest, i haven't messed around enough with your mod to actually know which transparent particles are the ones affected ^^U so even if they have to look wrong, i might not even notice them xDU. As u say, maybe corosus might find a way to make them both work, were you able to contact him? i could submit an issue on his github if that helps. I agree with your decision btw, i prefer that over not receiving any more updates ^^U

**Comment by Corail31** [comment]
Yes, you understand well. At the same time, weather2 makes the particles fly with the wind even if they are set to "no physics" so they are already broken^^
The incompatibility with weather2 (the dirty texture) comes from my change, so it doesn't worth to open an issue (and it's only about particle rendering, not really problematic as long as the 'soul' can be seen).
In the next release, i re-added my custom shader for when Oculus is not present (or the shaders are not enabled) which works fine with weather2, and i switch to the "patched particle shader" when shaders are enabled if weather2 is not present.
