### ISSUE TITLE
havent caught a lost tablet 1.14.4

### ISSUE THREAD

**Issue by dankdan02** [Corail31/tombstone_lite#156]
ive been fishing for a couple of hours and i still havent gotten a lost table. does enchanting the rod of misadventure with lure, agglers bounty or luck of the sea effect it? and also do you think upgrade aquatic may mess with the chance? it main only adds some new fish into the game that you can catch. thank you

**Comment by Corail31** [comment]
Hi dankdan02,
Normally, the rod of misadventure can't be enchanted in survival, and won't consider any luck/lure bonus.
If your objective is to find lost tablets, you need to be in the "fishing junk loottable" so, by having a bad luck provided by the rod.
Then, to test if the rod is really working, there's a config option named "chance_loot_lost_tablet" that you can set to the max (depending on the version it's 100 or 1000, but the config file shows the range) - even if it needs to be in the "junk" it should happen more often.
Also, in the newer versions, and to incite to explore the world instead of afk fishing farm, it requires you to fish in an area of 5X5 with "still water" (almostly similar to 1.16).
Keep me informed about your test after this :)
