### ISSUE TITLE
Balance-exploit/compatibility bug with EvilCraft (see also CyclopsMC/EvilCraft #979)

### ISSUE THREAD

**Issue by Twisted-Code** [Corail31/tombstone_lite#157]
### Minecraft Version

1.19.2

### Forge Version

43.2.6 (while playing ATM8), 43.2.11 (isolated test)

### Corail Tombstone Version

8.2.7 (while playing ATM8), 8.2.11 (isolated test)

#### Short description:

Potential balance-exploit, similar to an item duplication bug, in conjunction between Corail Tombstone & EvilCraft. Tombstone perk "Alchemist" boosts the duration of a potion when one is consumed, and the lengthened effects can be rebottled with an ``evilcraft:purifier` block.

#### Actual behaviour:

at the expense of three buckets of blood every time you do it, you can repeatedly extend the duration of almost any status effect, main exceptions being stuff like instant health and instant damage which instantly end when applied. This boost is multiplicative, not additive, and the function that describes its growth per bottling operation is f(l, x) = 0.1lx +x - 3 (where l is your level of alchemy and x is the number of seconds on the potion. The -3 is because the purifier takes 3 seconds to remove an affect). 

this interaction is what I would unequivocally describe as "Overpowered": within like 4-6 bottlings, so somewhere around 15 buckets of blood, I was able to get a 10 minutes buff scroll (which I also boosted with Scribe) up from the already-pretty-nice 15 minutes I would've gotten from Scribe... up to just over 3 1/2 hours! Screenshot:
![image](https://github.com/Corail31/tombstone_lite/assets/7110033/897c964f-7c90-4292-af2b-c655074f2f9c)

#### Expected behaviour:

DON'T let the player get infinite potion durations, at least not without a proportional cost. 
On EC's side of the fence: since CyclopsLib seemingly supports storages with very large capacities (2^16 times some unit, specifically), maybe the blood cost should be proportional to the duration of the potion (possibly adjusted by its value if you can determine that somehow)?
On tombstone's side: there could at least be a config option to disallow Alchemy from lengthening "uncraftable" potions. Honestly not sure what else to do...

#### Steps to reproduce the problem:

1. Install both EvilCraft and Corail Tombstone
2. keep doing things in the latter until you get at least one Knowledge of Death level. I don't think there is a debug command to give yourself KoD skill points, but I think you can just keep granting and revoking advancements from the mod. 
3. Make sure you have access to the Knowledge of Death perk menu one way or another, either by the Keybind or the chat message that shows when you level up
4. Open that menu and, using your KoD level, get a level of Alchemist
5. You can repeat step 2-4 to get higher levels of Alchemist for greater effect, but one level will suffice for this test
6. Obtain and place an EvilCraft Purifier
7. Place or pump blood into the Purifier. For this test, a creative source of blood pumped into the block's Fluid capability would be best so you don't have to keep refilling it, but failing that, any other method of bucketing blood into the machine will suffice. It needs to be full, though.
8. Put a bottle on top of the Purifier by right clicking it so the floating spinning item appears above the block model.
9. Give yourself a potion, either from Minecraft or any mod. I recommend at least one minute duration, maybe even more if you only have 1 level of Alchemy. If you've done everything correct so far, you should notice it has longer duration than you would expect from its item data (For instance, long_night_vision, which I recommend for this test, lasts 8:00 normally)
10. Stand in the purifier, and immediately drink the potion.
11. If the purifier is full of blood and a bottle and you are standing in it, the potion should be bottled up, now having a longer effect duration thanks to this exploit.

### Gametype

Singleplayer, Dedicated Server

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Other relevant mods

EvilCraft— Versions: 1.2.16 (while playing ATM8), 1.2.18 (isolated test)

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Sorry but i don't understand your topic, it's too long (but also because I don't know much about the other mod). Potion duration is increased when consumed by having the Perk Alchemist. The tooltip is for information if you would consume this potion with the current perk level. Potions are not really changed on their duration.
Also, if you care about potion duration, you're far to really see how unbalanced is modded mc (ex: players have tons of slots for equipable and each item can have tons of 'permanent' enchantments).
It looks more on the EvilCraft side as your story is about this purifier and their rebottled feature, i'll follow the [issue](https://github.com/CyclopsMC/EvilCraft/issues/979) on EvilCraft github. The list of commands are on my mod page, and exists to help tests (ex /tbknowledge[space][tab]).
Edit: If i understand well, i suppose the other mod could limit with a config the rebottled duration (like 'magic siphon' enchantment has a limit based on a config allowing players to define their gamestyle) or by adjusting the cost for rebottling high duration potions.

**Comment by Twisted-Code** [comment]
Not sure why you tagged this invalid, since I followed your issue template. Also did you basically just tl;dr me? It's long because I'm trying to give you as much information as possible. It's way better than the alternative, IMO, where someone just says "it broke, help" with no further information

**Comment by Twisted-Code** [comment]
I reported the issue here because although, as you pointed out, you don't actually change the data of the potion items, you also don't really have a limit on the perk's effect on your end. It's just a multiplicative function of baseduration * 1 + (0.1*perklevel). I think there should be some form of (configurable/optional) limit. Plenty of ways to do this, doesn't have to be a flat cut off.

**Comment by Corail31** [comment]
You got a response that mentions the case of permanent enchantments, and that it was a problem of bottling in the other mod.
The Knowledge of Death skill tree is not so easy to increase (except if it's already configured in an unbalanced way) and you can use the config perkScale if needed.
The problem being solved on the other mod, i have no point for such a debate.
NB: my main language being french, it was tagued as 'invalid' because you wrote a roman for something that can be explained shortly and by taking into account that the other person is not supposed to know all the mods, so i didn't get it on my first read (and tags are only tags... for issues).
