### ISSUE TITLE
Description for config option "no_grave_location" is unclear

### ISSUE THREAD

**Issue by Water-Moon** [Corail31/tombstone_lite#16]
### Minecraft Version

1.16.5

### Forge Version

36.2.0

### Corail Tombstone Version

1.16.5-6.5.3

### What happened?

So... I want to configure the mod to only create a grave in the overworld but not in any other dimension. 

I searched through the config and I found this entry called "no_grave_location" which apparently is the right tool.

 However, I did not find any information related to how I configure that except the one line that was there already, ["0, -300, 0, minecraft:overworld, 20"]. 

I could understand that's probably x,y,z,dimension,radius, and I did managed to get it work with something like "0, 0, 0, atum:atum, 128". 

However, two problem presist. First being that how can I configure that to be a whole dimension instead of a certain radius? (I tried -1 and it did not work). And also, how can I add more entry?

### Gametype

Singleplayer

### Happen with only Corail Tombstone

Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
This kind of features is not acceptacle because it would lead to modpacks having disallowed dimensions for grave and the players would report it as an issue in my mod. There's no reason to refuse a grave to appear as the objective is to protect the loots.
No grave locations are place with a radius in a dimension and you get a special message when it happens.
It's probably better to explain your use case to wish to disallow a dimension.
NB: if the description of this config is unclear, please check the french translation that is my main language or suggest a different text to provide for english.

**Comment by Water-Moon** [comment]
Understood. 

For my case particularly, I'm having a private server that I want some dimension to be more risky than others in the sense that the player will not get a grave when they died in them. 

For example, if a player died in the Atum dimension, their item will drop (instead of spawning a grave) and (as a result of item dropped) have a chance to be lost. 

I'm trying to find a way to do so but the only option I could get that is closest to what I mean is that configuration in your mod.

It would be the best if you can implement some config option that disallow grave spawning in certain dimension, and for the player to not consider it as a bug, maybe add a message for the case like "Grave spawning is not allowed in this dimension, therefore your item dropped on the ground". 

For the actual implementation, since I could not see the source of your mod, I could not help much, but my general idea is to add an `ArrayList` configuration for disallowed dimension. Then, when receiving a player's `LivingDeathEvent`, use `ArrayList.contains` to assess if they are in disallowed dimension. If so, the part for collecting drops and spawning grave can be directly skipped and instead a message will be displayed to the player saying they are in a dimension that grave can't spawn.

===

For the description, in English currently it is only explained as "Graveless Area", which is both a kinda awkward expression and also did not express what each parameter does. 

I would suggest to change that to "A zone in which no grave can be spawned", and explain its parameter with something like "Format: `["x, y, z, dimension, radius"]`".

**Comment by Corail31** [comment]
Sorry but player's graves are not an optional behavior like when you have a totem of undying, but the last ressort to protect items to be destroyed in lava for example. To my opinion, if you make such a server, players will just leave.
For the translation, it's a little more related to the fact that Forge didn't re-added a config in game since 1.12.2, and this translation exists as "tooltip" but is not displayed as i hoped this config to be back one day^^
NB: if it's really a private server and you know how to subscribe an event, you won't have trouble to achieve what you want (there's a grave if they're loots in the livingdropsevent at lowest priority).

**Comment by Water-Moon** [comment]
Sure, I'll maybe just implement the function myself. Thanks for the explanation!
