### ISSUE TITLE
Incompatibility: Welcome to the Jungle

### ISSUE THREAD

**Issue by Boymann** [Corail31/tombstone_lite#16]
Welcome to the Jungle causes the tombstones and the key not work anymore. You spawn without a key, and the tombstones don't work. Removing the mod solved the issue. There was no crash. They just didn't work together.

**Comment by Corail31** [comment]
Thanks for the report, i'll look their event code ;)

**Comment by Corail31** [comment]
I will make a provisory fix in next release. I don't why but welcome to the jungle seems to cancel all LivingDeath event.

**Comment by salvestrom** [comment]
hello there. my mod has a config option "keepSpeccial...". it is true by default, but when set false will ignore  the code causing the incompatability. the code keeps the mods armour on the player when they die which is fairly redundant when the player has a tombstone style mod. changing the config should restore your mods functionality.

**Comment by Corail31** [comment]
As i answered you in mp, with Tombstone, the soulbound feature can work without cancelling the livingDeath event (the tombstone events are often in lowest priority & the drops are only handle in the livingDrop event) and it works for mod like enderIO and ars magica 2.
You should at least check if the incompatible mod is present, when doing this & compare your soulbound code with others mods using soulbound)
For me, you shouldn't disable this feature when a grave mod is present, because it's possible to handle it. (and it's not redondant at all)

**Comment by Corail31** [comment]
@salvestrom : it seems that you also cancel the clone event.

**Comment by Corail31** [comment]
provisory fix for now in 2.3.0

**Comment by Boymann** [comment]
Thank you!

**Comment by Corail31** [comment]
You're welcome ;)
Don't hesitate to report others mod incompatibilities.
