### ISSUE TITLE
crashing on minecraft 1.20.1

### ISSUE THREAD

**Issue by WilliamBlaze** [Corail31/tombstone_lite#164]
### Minecraft Version

1.2

### Forge Version

47.1.0

### Corail Tombstone Version

Corail Tombstone 8.5.0 for 1.20

### What happened?

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2023-07-08 21:24:25
Description: Ticking entity

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
You didn't follow the template correctly by locating your issue (you report a bug happening with only Corail Tombstone but you provide a log with tons of mods instead of locating the problematic mods), so the issue is closed.
Read again your log, and contact the other mod to fix their entity capabilities.
NB: your log is removed because you didn't post it as a pastebin.
Edit: It was the related mod if i remember well.
https://github.com/JayZX535/iobaddons-mc/issues/4
