### ISSUE TITLE
[1,12,2] Corail Tombstone removes the ability to access any of the other advancements 

### ISSUE THREAD

**Issue by paulbevz** [Corail31/tombstone_lite#165]
### Minecraft Version

1.12.2

### Forge Version

Most recent forge version

### Corail Tombstone Version

4.6.2

### What happened?

] Corail Tombstone removes the ability to access any of the other advancement

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

Better Advancements

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by paulbevz** [comment]
Here's a screenshot

**Comment by paulbevz** [comment]
Woops accidentally closed, my bad. [Here's a screenshot of the issue](https://imgur.com/a/KM68LsK)

**Comment by paulbevz** [comment]
[Modlist](https://imgur.com/a/GGcOM5A)

**Comment by Corail31** [comment]
Don't bypass the suggestion for supported versions.

**Comment by paulbevz** [comment]
What, why? This issue makes advancements unusable and it's for the 1.12.2 version of the mod... What else was I supposed to do?

**Comment by Corail31** [comment]
1.12.2 exists from ages, and have no trouble. So start by looking your other mods.
This doesn't change that 1.12.2 is not in the list of supported versions for github.
Supported versions are based on the popularity of those versions and 1.12.2 is less used by players unlike 1.16.5 or 1.19.2.
Besides, Forge doesn't support 1.12.2 since years.
