### ISSUE TITLE
Please blacklist disenchanting tetra tools because of infinite enchantment levels

### ISSUE THREAD

**Issue by TeeMee123** [Corail31/tombstone_lite#167]
By disenchanting a tetra tool with say fortune 6 from fortune 3 on each head, you get a fortune 6 book, which can be used on both heads of the pick to get fortune 12, and so on.
This breaks server economies if anyone discovers it.

**Comment by Corail31** [comment]
Hello teeMee, mods that enhance enchantment level expose them to this kind of bug.
I already answer to this kind of question [here](https://github.com/Corail31/tombstone_lite/issues/85).
I suppose Tetra has also trouble with the grindstone.
NB : there would be a way to do it like Hellfire proposed for Astral Sorcerry by not empowering the item when a book of disenchantment is in the left hand, or i could just blacklist the items of this mod for this behavior.

**Comment by mickelus** [comment]
Tetra has the same issue with grindstones, I've not figured out how to deal with it yet. Forge doesn't seem to fire any event when you disenchant items in a grindstone, otherwise we could have used something like that.
My best guess is to just blacklist tetra items from being disenchanted :/, the following item IDs from tetra can hold enchantments:
```
"tetra:modular_sword"
"tetra:modular_bow"
"tetra:modular_double"
"tetra:modular_single"
```

**Comment by Corail31** [comment]
@mickelus my objective is not to be incompatible with your mod (the last issue was more about the way to do it).
For now, i'll suppose that only heads can have enchantments (not being enough informed), and they are not always both enchanted on the same time ? (one part can be enchanted when the other is not, i suppose)
If it's the case where they don't have the same enchant/lvl, i would just need something in an api when it's one of your item to know the separated enchantments, so i could access it instead of looking the enchantments in the vanilla helper.

**Comment by mickelus** [comment]
Oh, yeah! I can try to put together an API! It will take me a few days to figure it though!
