### ISSUE TITLE
Rubidium v0.7.0a crashes with custom ShaderInstance

### ISSUE THREAD

**Issue by Gbergz** [Corail31/tombstone_lite#168]
### Minecraft Version

1.20

### Forge Version

47.1.3

### Corail Tombstone Version

8.5.2

### What happened?

I died, then crashed. Started happening on the newest Rubidium(Sodium) version 0.7.0a.

### Gametype

Singleplayer, Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No.

### Occurence

occurs all the time

### Other relevant mods

Rubidium

### Log Link

Crash Report: https://gist.githubusercontent.com/Gbergz/b4ab8a592cf540a56a12b9007189fb67/raw/22614491706a6920e296b9424b58b85fe79d38b1/gistfile1.txt

Logs: https://gist.githubusercontent.com/Gbergz/6bb8f3725ce81a118c3e5ed5719e5ec2/raw/e19553a39d428b0ac61d2835f2fd1ee467a2b797/gistfile1.txt

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

### Notes
Maybe this isn't because your mod, but thought I'd report it anyway.

**Comment by Corail31** [comment]
Hi Gbergz, it's been a while ^^
It looks related to the smoke particle and Rubidium (i was able to make it happen in workspace).
I didn't change my code and i even test without my mixin on Program class but it's not related.
I suppose the problem is coming from the Rubidium changes in their last version and they probably know how to fix it, so i recommand you to open an issue on their github.
For a provisory solution: don't update to latest rubidium ^^

**Comment by Gbergz** [comment]
Hey.
Gotcha, I will open an issue on their issue tracker.

And yep, the newest Rubidium update broke a bit of mods, trying to report issues to mod devs to see if its Rubidiums own fault or similar.

Thanks for answer.

**Comment by Corail31** [comment]
https://github.com/Asek3/Rubidium/issues/571
https://github.com/Asek3/Rubidium/issues/577
