### ISSUE TITLE
Familiar Receptacle and captured mob drops

### ISSUE THREAD

**Issue by DerShendi** [Corail31/tombstone_lite#177]
### Minecraft Version

1.19.2

### Forge Version

40.2.10

### Corail Tombstone Version

7.6.5-1.18.2

### What happened?

If you give your familiar anything to hold and kill it, it dies and drops everything. But when you revive it then it respawns with every item it held

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by DerShendi** [comment]
there wasnt a selection for 1.18.2 so i choose 19.2 sorry

**Comment by Corail31** [comment]
It's probably not a "vanilla mob" but a modded one. Captured mob in Familiar Receptacle have no inventory except if they were found as loot with already a tamed animal in. 1.18.2 is a not a problem as long as you make the test on the version that you mention (1.19.2).
Also, note that the Familiar Stone, which is a different item, and being "nearly" a creative item, recovers the inventory (and corresponds to the command /tbReviveFamiliar).
If you can give me the steps to make this happening without other mod (or only one mod), i could have a look on it.
If you want to make fast test, you can use the command /tbKnowledge with some params to reset the ankh.
https://github.com/Corail31/tombstone_lite/issues/119

**Comment by djnifos** [comment]
1. Have 2 familiar stones
2. Tame a trader llama.  
3. Right click a chest onto it, and put a familiar stone (and anything else) in the chest.
4. Kill the llama. 
5. Llama drops the stone, you have 2 again
6. Use the stone.  
7. Llama has it (and whatever else) in the chest
8. 
Tested with only JEI and  tombstone-8.5.1-1.20.1

I assume this will work with normal llamas, donkeys, mules, horses, and camels in just base minecraft.

**Comment by Corail31** [comment]
"Also, note that the Familiar Stone, which is a different item, and being "nearly" a creative item".
@djnifos The issue is normally about Familiar Receptacle as i don't think it's possible to find easily Familiar Stone without taking it in creative inventory, it's explained on #119 (Seeker Rod sold by the Grave Guardian with reward chance and the Villager Gift during Christmas. The Seeker Rod loottable being editable in the save folder). Closed to let time to read my answer.
@DoctorMage I'll keep in mind to change Familiar Stone for "survival mode" (like in versions 1.19.3+) soon for your initial issue for 1.16.5/1.18.2/1.19.2.

**Comment by Corail31** [comment]
@djnifos Your comment was incorrect, 1.20.1 is working [differently](https://github.com/Corail31/tombstone_lite/commit/92c3d510a83537bfbca7aae3e57b492477b6855f) (Familiar Stones are already adapted for survival mode)... Don't bring wrong informations. The change is now available in the new release 1.16.5/1.18.2/1.19.2.
