### ISSUE TITLE
Enchanted Grave Key never Enchanted with config on 100%

### ISSUE THREAD

**Issue by HireSLH** [Corail31/tombstone_lite#178]
I have a 1.15.2 server with Forge 31.2.0  and Tombstone 4.3.8 There are more mods installed.
chance_enchanted_grave_key = 100 but if you die you never get a Enchanted Key its allways disenchanted and i don't know what happens because in older versions it works but on last update is broken. I also try it on single player World and its the same.
I just realized that when I reset the server the setting change to 0. How i can fix it to 100?

**Comment by Corail31** [comment]
Hi HireSLH, you should check this [topic](https://github.com/Corail31/tombstone_lite/issues/163).
If your editor is not ideal, it won't work.
NB : this feature is known to work so that's why i don't even consider this possibility. You can check if the perk "Jailer" is present, it means your config is not set on 100.

**Comment by HireSLH** [comment]
I was using windows notepad, after reading that topic i download Notepad ++ and check UTF-8 without BOM and reset it on 100 and its solved. lol i cant belive notepad was the problem I always edit settings with that, now I'm afraid of what else I've broken
