### ISSUE TITLE
Easter Eggs

### ISSUE THREAD

**Issue by ghost** [Corail31/tombstone_lite#208]
### Minecraft Version

1.20.1

### Forge Version

47.2.20

### Corail Tombstone Version

8.6.4

### What happened?

I have not found an entry for disabling the easter eggs in the configs. Also just started appearing from one day to the next. They spawn in all dimensions in ATM9 and get sucked up by magnetic augments etc. Just annoying entities all over the place. 

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Other relevant mods

ATM9

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
They only spawn around players, not in all dimensions, with a random chance and they disappear after a moment like any entityItem (5min). They have no reason to be disableable.
I'll add a config to change the rarity but they have been tested to be 'not so common'.
Edit: solved in 8.6.5 for 1.20.1.
As precision, if i spent time to create an event for Easter, i don't see why to remove the main ingredient used to trade with the Grave Guardian and also used in a cooking recipe as the code can be adapted to be less invasive.
The fact you had your eggs in all the dimensions was probably related to your modpack and the code has been changed to not use the playertick event. If you set the config to 100000, you won't probably see the eggs.
If you really don't want the Easter event, you can simply stay on version 8.6.1.

**Comment by KiriKaz** [comment]
I don't quite understand why it is that the option to remove the easter eggs is not available. Nor what you mean when you say "they've been tested to be not so common".

**Comment by Corail31** [comment]
You have to read to understand, when i say 1 chance on 100000 means no egg (or one every hour).
If there's a badly intentioned mod that is doing an additional thing, it's perhaps time to find it (because not everybody has raining eggs... only thoses on ATM modpack).
Some people didn't understand why others complaint as they have not even seen one egg...
You can also revert to 8.6.1 as i suggested if you don't want the event, so you are really in bad faith about this.
**Anyone can test the mod without others mods to see the normal behaviour.**
So, stop spreading rumors because yes, it has been tested and i'm sure what my code does.

If i make a mod, it is for players who understand that it is not just a grave mod and that there is an associated gameplay and who do not wish to deactivate the slightest functionality despite the fact that I give this possibility (and that some still manage to complain).

So, end of drama and trolls for a whole month, i also read reddit.
Old players know how to contact me on CurseForge page if needed.

**Comment by Guigui220D** [comment]
Please reconsider: when you have a lot of machienry, those eggs spawn in your conveyor belts and get everywhere

**Comment by Guigui220D** [comment]
When you have a magnet mod, your inventory gets filled annoyingly, also
