### ISSUE TITLE
weird death glitch

### ISSUE THREAD

**Issue by Orangejewce92** [Corail31/tombstone_lite#223]
### Minecraft Version

1.20.1

### Forge Version

47.2.30

### Corail Tombstone Version

8.6.5

### What happened?

on death you dont get a key. and you cant interact with block breaking. when you get to your grave (without a summoned key) you go into a death loop.

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Log Link

https://pastebin.com/ehmXwuX5

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Orangejewce92** [comment]
tested alone. issue does not occur. hopefully the pastebin is enough to resolve. if more info is needed please lmk asap !

**Comment by Corail31** [comment]
Your log seems to be related to Blood Magic and a Curios compat in that mod.
If you're on Mohist or an hybrid server, it's possibly related too, you can search similar "closed" issues about hybrid server by selecting the tag here.

**Comment by Orangejewce92** [comment]
i'm in singleplayer and i removed bloodmagic to test it and it still happened.
i'm also running through curseforge launcher

**Comment by Orangejewce92** [comment]
also a grave spawns in but no key on respawn. cant break blocks and when you get to your grave you die again. into a loop. no hybrids strictly forge. on curseforge launcher and in singleplayer

**Comment by Orangejewce92** [comment]
i was mistaken. i removed bloodmagic and went into the same world and the issue still occurred. removing blood magic and creating a new world, i still get the same Glitch. so the issue is blood magic thank you for confirming. 

When you say its a curio compat issue, would that just be in the datapack version of the mod right? so i should be able to remove that.

i guess if i figure it out i can post a fix here for others.

**Comment by Orangejewce92** [comment]
i dont know how to do PR's but i fix their code for the crash 

https://github.com/WayofTime/BloodMagic/issues/2040

hopefully its resolved fast

**Comment by Corail31** [comment]
No key is already abnormal meaning that some Forge events are not fired (and also strange if you have a grave and no key because they're set at the same place, so maybe something happening in the respawn event when they key is restored in the player inventory).
You also don't need a key to open a grave. Note that graves can only be breaked in creative mode, you just need to right click them or use "crouching" to get the content of a grave (crouching is a good alternative to test if it's related to a "permission mod").
If you're not on a hybrid server, you will have to reduce your mod list to locate the problem (the fact you die in loop is for sure not related to my mod).
There're lots of chance that you have more than one issue in your modpack (the loop death, the fact to not be able to open a grave and to receive a key are for me 3 differents things).

**Comment by Orangejewce92** [comment]
Issue only persisted with blood magic added. Removed no problem
