### ISSUE TITLE
Grave did not spawn no key was given

### ISSUE THREAD

**Issue by Jack-0-Spades** [Corail31/tombstone_lite#226]
### Minecraft Version

1.20.1

### Forge Version

47.2.0

### Corail Tombstone Version

8.6.5

### What happened?

While fighting a Mana and Artifice undead boss the wither lord I died. I respawned with no key. On heading back to the arena no tombstone had spawned. This boss is fought in a unique location that is protected from destruction. I had died twice there already and my grave spawned in fine. The only thing I think of is if the grave tried to break  some of the  "underweed" a type of grass that had spawned from Alex's Caves inside the arena, and when the area protection reverted the change the grave was destroyed. I don't think anything is the fault of your mod here but considering what happened maybe it would be a good idea to add a way to get your stuff back if the grave gets destroyed.  like detection for the grave getting destroyed and some type of failsafe?

As always thanks for your time and efforts.

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs rarely

### Other relevant mods

Mana and Artifice

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hi, you should try to reproduce the issue with a minimal amount of mods, this allows to make sure what is the problem and if it's not related to others mods. Graves can't be destroyed (you can try with a command setblock), only a player in creative mode can break graves. Also, if a grave couldn't place, you would receive a message about it (and the drops would still drop).
The more common case when there is no grave is if there is no drop (due to others mods) or when a mod kills strangely a player (leading to no drop).
You can use the command /tbrecovery to get your drops (which is done sooner than the 'drop' forge event).

**Comment by Xiantrius** [comment]
We have a PvE server here. This also happens when standard mobs like witches, skeletons, creepers, etc. kill the player. I don't know how this happens, which means that even with smaller mod numbers it becomes difficult.
Can you maybe give me a tip as to which mods in my list are most likely to cause the problem?

**Comment by Corail31** [comment]
@Xiantrius Your problem is related to Hybrid Server(Ketting) so, no relationship with this issue (#231).
