### ISSUE TITLE
Curse of Bones invulnerability bug after max level passed with Apotheosis 

### ISSUE THREAD

**Issue by ThePhoenixIO** [Corail31/tombstone_lite#233]
### Minecraft Version

1.20.1

### Forge Version

47.3.1

### Corail Tombstone Version

8.6.6

### What happened?

With Apotheosis installed, the Curse of Bones enchant was able to be applied to armor beyond the typical level V maximum (Level XIII).

This resulted in the player casting curse of bones every time after a single hit where they would only take a maximum of 10 damage pts. After Curse of Bones was cast the player would become completely invulnerable until curse of bones wore off.

The enchant must be applied to the armor and the attack must initiate any enchant on the armor. Bypassing armor protections results in a normal attack.

While I can't confirm due to being unable to see the source code, I believe this is due to how the chance for application of Curse of Bones is implemented with the percentage chance and damage negation being tied to the level without a cap on the max level can be.

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

Apotheosis

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hi ThePhoenixIO,
Even if Apotheosis hooks in this enchantment, it won't change how it works (the progression scale will just be different).
The chance to proc is 100% if the Curse of Bones is level 10.
It's not a problem because there is a cooldown preventing to get again the Curse of Bones.
But, the cooldown reduces if the enchantment has a higher level (from a scaled range between 56 seconds and 20 seconds).
So, i suppose you mean that you do 10 damages during theses 20 seconds.

I have a question for you : what should be the ideal time of cooldown (a range based on enchantment level) when the Curse of Bones ends ? I could adjust with a config then.
I'm also open to any suggestions to make the enchantment more configurable.

Additional infos:
1. The reflected damages of Bone Shield are also 100% if the Curse of Bones is at level 10
2. The Bone Shield can't reflect thorn/projectile/explosion damages (so, if you can do this kind of damages, it will help you)
3. Ideally, you have to avoid to hit the player when the Bone Shield is active (as he can't get damages except thoses mentioned above)
4. The damages of Bone Shield are Thorn, so if you have a way to reduce theses damages, it can helpfull

**Comment by ThePhoenixIO** [comment]
Thanks for the insight. I think having a config for that would be useful but I'm not sure if that is specifically causing the issue that way servers could balance the enchant to the other mods they have on the server; because if I understand how the enchant works, the higher the lever the better chance (up to 100%) the curse will activate the shield and also the higher the enchant the lower the cooldown as to when the shield can be activated again. Again if I am understanding how it works, there could be a loop where a player is effectively immune to damage as they will always activate the shield and quickly regain the ability to activate it again.

Also for some further clarification as to how I noticed this once I hit the player with the curse of bones enchant they only took 10 damage pts in well over a min with a chest plate enchanted with level 12 curse of bones. The sword used in the attack had over 170 hit points of damage.

Also I did some further testing and it looks like the cooldown is uncapped so after level 10 the cooldown becomes very short. At level 11 the cooldown is only around 6sec and at 12 and 13 there is no cooldown. Also in testing thorns (at least at very high levels) doesn't cause damage to the player who has the bone shield active.

**Comment by Corail31** [comment]
I think you understood it correctly.
But the enchantment has really a limit of 20 seconds for the cooldown (except if another mod is changing something).
The formula is 60 seconds - (40 * level / maxLevel).
So, except if Apotheosis allows higher levels without changing the getMaxLevel() of the enchantment, i don't see how it would be possible (and it wouldn't be logic because it would would prevent to scale properly and would force to cap the level of the enchantment making the additional levels useless).

**Comment by ThePhoenixIO** [comment]
Interesting, It must be another mod influencing it then, but I have to wonder what mod and why it would cause that hard limit to go to 0.

If you would like I could get you the link to the modpack on CurseForge I am maintaining, though I am not sure that would be helpful, and I may just need to disable the enchant due to the weird interaction.

**Comment by Corail31** [comment]
I don't test modpack, but you can test in a singleplayer game with only Apotheosis and my mod to get better conclusions.
Additionally, you can limit enchantment level in Apotheosis.

**Comment by ThePhoenixIO** [comment]
> I don't test modpack, but you can test in a singleplayer game with only Apotheosis and my mod to get better conclusions. Additionally, you can limit enchantment level in Apotheosis.

I didn't think you would want to test the pack, but thought I would offer. Maybe it is just a weird interaction between Apotheosis. And thx for the tip on limiting the enchant level, that also seems like a good option for pack balance.

**Comment by Corail31** [comment]
I'll probably add some configs for that enchantment, i like to tweak a little from time to time as long players bring my attention on things :p

**Comment by ThePhoenixIO** [comment]
Yeah its fun to see some small tweaks here and there. And thx for helping debug this, I've been using the mod for years and is one of my gotos when I build packs.

**Comment by Shadows-of-Fire** [comment]
Apotheosis does not update the value of `Enchantment#getMaxLevel` (doing so would require individually applying a mixin to every child class of `Enchantment`) - so if you are relying on it reflecting the "real max" that won't happen.

Your hard limit should be absolute, not something that tries to scale with the ratio of real level / max level, i.e. checked via `Mth.clamp` or similar.

**Comment by Corail31** [comment]
@Shadows-of-Fire Thanks for your answer, it clears things up :)

**Comment by Corail31** [comment]
@ThePhoenixIO If you want a version to test the changes (same formulas, 6 additional configs for armor enchantments and taking in account the max level of Apotheosis), you can contact me on CurseForge.

**Comment by ThePhoenixIO** [comment]
@Corail31 Will do
