### ISSUE TITLE
Diamonds not crafting in inventory w/ bone needle

### ISSUE THREAD

**Issue by ChunkBannedPanda** [Corail31/tombstone_lite#236]
### Minecraft Version

1.20.1

### Forge Version

47.3.0

### Corail Tombstone Version

8.7.0

### What happened?

just started playing the mod in my current 1.20.1 pack, when impregnating a needle with demon wife from occultism (tested vanilla mobs as well) i am unable to craft the needle with the diamond like you would to make a familiar receptacle.

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
You just need to right click the impregnated diamond with the bone needle in inventory (for info, command /tbgui compendium combination).
Maybe the crafting recipe will be re-added in the future but, the main point to combine in inventory is you receive message when the craft is not fitting, for example by trying to enchant a grave key already enchanted (instead of just an empty stack with the Crafting Table).
Note that you can use a normal diamond for the familiar receptacle recipe (the impregnated is to limit to "capture/save" this kind of creature).

**Comment by ChunkBannedPanda** [comment]
this was not my issue in the slightest.

the 'combine in inventory' function was not working, the crafting grid was not used nor do i think it fits with the 'combine in inventory' system you have set up. 

i have since reinstalled all required items for your mod to function and it seems to have worked as a band-aid solution if it comes up again i will leave an issue report with more detail i suppose.

**Comment by Corail31** [comment]
If you have the combination not working, it can only be a mod preventing it (kind of mods like MouseTweaks).
Also, the Bone Needle has a countdown before 'losing' the name of the entity but in this case, you would have a toast message about the reason (again, if a mod is not preventing toasts).
Note that i answer based on the provided infos (so, with the fact that _you were able to make it happening with only my mod_), and your message was not enoughly precise.
> i have since reinstalled all required items for your mod to function and it seems to have worked as a band-aid solution if it comes up again i will leave an issue report with more detail i suppose.

-> this sentence is strange to me as my mod only needs to be in the mods folder.
