### ISSUE TITLE
Suggestions for Alignment

### ISSUE THREAD

**Issue by katubug** [Corail31/tombstone_lite#239]
### Minecraft Version

1.20.1

### Forge Version

47.3.7

### Corail Tombstone Version

8.7.1

### What happened?

Hi! I'm putting this in by request so it's not just in the CurseForge comments. I am not sure, off the top of my head, if I can use loottable alignment rewards with KubeJS. But I definitely know I can execute commands, so I would love the ability to increment and decrement alignment that way. My suggestion was this:

`/tbknowledge HeyKatu alignment add 0.01`
`/tbknowledge HeyKatu alignment add -0.20`

If -5 is full Dark and +5 is full Light, I think it makes the most sense to be able to change it in small increments.

These are the ideas we mentioned for other things which could change alignment -

**Good Alignment**:
- Feeding/Healing Tamed Animals.
- Bonemealing Plants.  (Maybe have this be on a cooldown?)
- Breeding Animals.
- Trading with Villagers.
- Using Earthly Garden effect. 
- Cooking/Crafting food (for me, this is using the Crock Pot mod, so I don't expect you to add compat for it.)

**Bad Alignment:**
- Hurting tamed animals. (this way if a player tries to farm good alignment by hurting and healing their pet, it cancels out)
- Killing tamed animals.
- Hurting baby animals.
- Killing baby animals.
- Breaking village bookshelves(? not sure on this one, it might be too harsh.)

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone on Forge (required)

No

### Occurence

occurs all the time

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Actually, the alignment points have a range from -500 to 500.
If it's to have the possibility to reward a little smaller actions, i would prefer to increase theses numbers (multiplied by 10 for example) instead of using decimal values (and rewards more the existing actions to compensate).
But, i'm ok to change the command to increase/decrease slowly.

The current rewards are : (and have configs to set the amount)

**Good alignment**
- use a soul receptacle on a grave to free the soul
- kill a raider (raider tag or zombie from "village siege" or Phantom)
- use exorcism on a zombie villager
- use protection (on villager/golem/player)

**Bad alignment**
- plunder an abandoned player grave (accessible to all after the decayTime)
- kill a villager
- use zombify on a villager
- use a Tablet of Cupidity

I can add some of your ideas about alignment rewards (but not all, you could still add the others with KubeJS).
I'll probably add the command in the next release and some ideas not requiring cooldowns (not being exploitable), and look for the others in a future release.

**Comment by Corail31** [comment]
I started to add the main changes:
- new command /tbalignment <show|set|increase|decrease>
- displays message for alignment increase/decrease
- client config to allow to display the alignment message
- changes the command /tbknowledge
  - "set" parameter is used to define the wanted level in Knowledge of Death
  - "give/remove" parameters are replaced by "increase/decrease"

**Comment by katubug** [comment]
This is all amazing! Thank you so much!! I can't wait to get this integrated :)

**Comment by Corail31** [comment]
@katubug I can already send you a "test version" on CurseForge if you want to start to prepare your modpack.
But, i still wait to know if this is correct for you ("multiplied by 10"):

> If it's to have the possibility to reward a little smaller actions, i would prefer to increase theses numbers (multiplied by 10 for example) instead of using decimal values (and rewards more the existing actions to compensate).

**Comment by katubug** [comment]
Oh, sorry for not responding to that! It's been a rough day haha. Yes,
that's fine, I only suggested the decimals because I thought it was a
smaller scale. The scale of whole numbers up to 500 is perfect!

I'm happy to receive a test version! That would be lovely, thank you! I'm
about to go to bed for the night but I would test it in the morning. :)

**Comment by Corail31** [comment]
@katubug It's morning for me :p It will be a range from -5000 to 5000 (i could even go to 10000).
I sent you the message for the test version on CurseForge.

**Comment by katubug** [comment]
Good morning, haha! And 5000 to -5000 is great :D

**Comment by Corail31** [comment]
To resume the whole changes (as i think it will be enough for now and you can add the others with KubeJS):
- new command /tbalignment <show|set|increase|decrease>
- displays message for alignment increase/decrease
- client config to allow to display the alignment message
- changes the command /tbknowledge
  - "set" parameter is used to define the wanted level in Knowledge of Death
  - "give/remove" parameters are replaced by "increase/decrease"
- changes alignment range (-5000 to 5000 instead of -500 to 500)
- adjusts the config default values for alignment point rewards (it's recommanded to reset the config)
- rewards alignment points when using Potion of Earthly Garden (+10 by default)
- rewards alignment points when killing your tamed creature (-10 by default)

**Comment by katubug** [comment]
Amazing, thank you so much! I'll update as soon as it's available!

**Comment by Corail31** [comment]
It's published (8.7.2 for 1.20.1).
