### ISSUE TITLE
IllegalAccessError when accessing loot pools

### ISSUE THREAD

**Issue by FluxAeternia** [Corail31/tombstone_lite#240]
### Minecraft Version

1.20.1

### Framework Type

Forge

### Framework Version

Multiple

### Corail Tombstone Version

ive tried them all

### What happened?

Im crashing upon creating a world, with a very odd error. That doesnt seem to point to anything that is actually the issue. Ive changed forge versions and game versions over and over trying them all I think. And nothing stops this error. ive disabled the mods it lists and nothing changes. The only thing that stops it is removing the mod entirely and i really like it so i would prefer to figure out why its erroring instead of not using it.

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone on Forge (required)

No

### Occurence

occurs all the time

### Log Link

https://pastebin.com/Kz9FjAvy

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
I'm sorry for you, but you use tons of mods and the log is not enough to know the reason why the accessor is not working.
It works perfectly without your other mods and you will have to search in your others mods which one is conflicting.
This accessor is used since at least 1.16.5... ^^
Additionally, lots of players use 1.20.1 and don't have your problem so **your explanation is not true** and you're a new github account. If you're lazy to test to remove your other mods, don't open an issue then.

**Comment by RaphaNinja10** [comment]
I have the same error in my modpack. Tried all 1.20.1 version and the error maintains.

**Comment by Corail31** [comment]
@FluxAeternia @RaphaNinja10 Whatever was the problem with your modpack, it can no longer occur with the latest.
