### ISSUE TITLE
Necromancer disabled

### ISSUE THREAD

**Issue by Baermey** [Corail31/tombstone_lite#241]
### Minecraft Version

1.20.1

### Framework Type

Forge

### Framework Version

47.3.7

### Corail Tombstone Version

8.7.3

### What happened?

no matter the config setting. the necromancer perk remains in a disabled state 

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone on Forge (required)

Yes

### Occurence

occurs all the time

### Log Link

https://pastebin.com/sScRWrCD

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hello Baermey, i checked it and it works fine.
The only detail that i noticed is that the tooltip on the perk doesn't mention that you need a bad alignment to use it (at least -1) , and i just changed this tooltip for next release.
The 'disabled condition' was changed in latest version because it wasn't disabled when alignment was good/neutral and mentioned in the changelog:
> - fixes necromancer disabled condition

Note that you can verify it by using the command: /tbalignment [playerName] set -1
Also, the perk Necromancer has no use for good alignment player, as it's only used for prayer to tame undeads.

**Comment by Baermey** [comment]
That would make sense, fair enough
Should of investigated further, but the tooltip threw me off

**Comment by Corail31** [comment]
@Baermey 8.7.4 provides more infos for disabled perks ;)
