### ISSUE TITLE
Duplicate

### ISSUE THREAD

**Issue by RaphaNinja10** [Corail31/tombstone_lite#249]
### Minecraft Version

1.20.1

### Framework Type

Forge

### Framework Version

47.3.11

### Corail Tombstone Version

8.8.0

### What happened?

After server world gen, server stop itself returning a crash report.

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone on Forge (required)

No

### Occurence

occurs all the time

### Log Link

https://pastebin.com/raw/9dyjvy5P

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
You missed to locate which mod is causing my mixin accessor to not work.
Duplicate of https://github.com/Corail31/tombstone_lite/issues/240
But as long it's not located, i can't help you (in 1.21, i can use Access Transformer but not in 1.20.1 and below).

**Comment by RaphaNinja10** [comment]
Without tombstone all works fine

**Comment by RaphaNinja10** [comment]
how can I locate it?

**Comment by Corail31** [comment]
Logic as i'm the one using a mixin accessor (and is present since 1.16.5), but it doesn't change that you have tons of mods and only one is needed to crash the other mods.
Reduces your mod list until you don't have a crash (or still have the crash) with my mod (as usual).
You missed the part of the "issue template" to find the mods involved to make the bug (if you use only my mod, it won't crash) and it's not optional. You can also compare the mod list on the other issue.
If you locate the involved mod, i could re-open the issue and test it myself.

**Comment by RaphaNinja10** [comment]
I could not find the mod causing that issue... Can I send you my modpack link for you to take a look? I really want to use your tombstone mod

**Comment by Corail31** [comment]
No, it's to you to make this sort, or your modpacker.
If you have been wise while adding your mods, you wouldn't be searching now.
"I couldn't find" means you're lazy to do it, the best that i can do is to encourage you to find that mod (or at least reduces your modlist).
I tested 'some' of your modlist (like Lootr) but all was working fine but your modlist is really too long (and lots of mods use mixin on LootTable without trouble with my mod).

The best way is to separate your modlist in 2 and test each part with Tombstone to see which one crash and continue then with the part crashing to separate again in 2.
The other way is to comparate the 'other issue' modlist and looks thoses being in the 2 reports.

Note that if it's a bad 'core' mod (using asm) making this error, i will make that mod incompatible.

**Comment by RaphaNinja10** [comment]
I hadn't this error with this modpack before... and pls stop making conclusions that i'm lazy and not wise, because if I was lazy i wasn't trying to solve that until now.

**Comment by RaphaNinja10** [comment]
One thing that i did not mention is that this error is only in server and it does not occurs in the client. Playing in single player I can create a world and play normally.

**Comment by Corail31** [comment]
I give you a last chance, to answer to questions above instead of controversy (if you have a grave key, if you get a message from Tombstone on death, and to locate your 'incompatible' mod), after i lock this issue. You don't try to solve anything for now.

**Comment by Corail31** [comment]
If it's a modpack: reports to them the issue. The issue template asks to **locate the incompatible mod** if it's not happening with my mod alone. It's that how it works, **or the issue is invalid**: i don't debug modpacks.
Then, if you hadn't this error happening before, just looks the changes in the modpack before you updated it (my code being the same since a long time, since 1.16.5).
