### ISSUE TITLE
Last resort for grave position can be different from grave key position

### ISSUE THREAD

**Issue by schindlershadow** [Corail31/tombstone_lite#256]
### Minecraft Version

1.21.1

### Framework Type

NeoForge

### Framework Version

21.1.61

### Corail Tombstone Version

9.1.2

### What happened?

If a player dies on a lava lake in the nether or on top of the nether far from the bedrock, a grave is not spawned. 

no grave key is given to the player

the grave location displayed in chat is the position of their respawn point

I am also unable to restore the players grave with commands, it just teleports them where they died
`/tbrecovery load_player <playername> .latest`

this is the only log:
`[17:49:07] [Server thread/INFO] The player <playername> has successfully been saved`

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone on Forge (required)

No

### Occurence

occurs all the time

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
I made lots of tests and there is always a grave in lava lake so it's not the real problem.
I'll make more tests as it can be when there is no place for grave and it chooses your respawn point as a last resort.
Also note that the command /tbrecovery is separated from the grave handling and works properly (you probably used the parameter save_player instead of load_player).

**Comment by Corail31** [comment]
@schindlershadow Ok, i finally got it.
When there is no place for grave, it used the last resort (the respawn point).
But if this respawn was in another dimension, the grave was created with the actuel dimension (unintentional) and the grave key had the other dimension position: meaning the grave key disappears due to no grave at this position, but the grave was really created but in the initial dimension (since release 9.0.3).
