### ISSUE TITLE
Informations to prevent grave's key to be automatically enchanted during Halloween

### ISSUE THREAD

**Issue by davidjimeneztv** [Corail31/tombstone_lite#259]
### Minecraft Version

1.20.1

### Framework Type

Forge

### Framework Version

47.3.11

### Hybrid Server

Mohist

### Corail Tombstone Version

8.8.3

### What happened?

I have set the `always_enchant_grave_key` option to disabled (`false`), but despite restarting the game and testing again, the enchanted key is still given to all users immediately after they die.

I have also disabled the crafting of this key, but the issue persists. No errors appear in the console.

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone on Forge (required)

Yes

### Occurence

occurs all the time

### Other relevant mods

PlayerRevive, EnhancedVisuals, 

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
I think that you misunderstand the config "always_enchant_grave_key": it makes the key always enchanted if the option is enabled (it doesn't say that you will never have an enchanted key).
During Halloween, grave's keys are always enchanted (because each player has a bonus in the perk "Jailer".
So, the way to disable this, is to disable the perk "Jailer" in the server config by setting "allow_jailer" to false.

**Comment by jojoblackFr** [comment]
sorry to bring back this post but do you think you can add a ways to disable those bonus perk ? or even the event themself ?
