### ISSUE TITLE
[1.17.1/7.2.4] fix_anvil_custom_name breaks anvil custom names

### ISSUE THREAD

**Issue by DaemonUmbra** [Corail31/tombstone_lite#26]
### Minecraft Version

1.17.1

### Forge Version

37.0.103

### Corail Tombstone Version

7.2.4

### What happened?

Attempting to rename a nametag or other item does not work when ``fix_anvil_custom_name`` is set to true on the client, the renamed item appears in the slot but attempting to take it resets the name and cancels the crafting process.

I tested this by attempting to knock the last letter off of nametags and anvils, it did not work until I disabled the config option and restarted my client.

### Gametype

Singleplayer, Dedicated Server

### Happen with only Corail Tombstone

Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hi DaemonUmbra,
The trouble is this bug exists since 1.13.2 (and i waited a long for forge to make a fix), the 1.12.2 code is not different from the current code.
Edit: thanks you for reporting it, i just check it (the config to disable it needs to be set on the client). You can ask to Raycoms if you want to see the new solution as obviously i would prefer a solution in forge.

**Comment by Corail31** [comment]
fixed in 7.2.5
NB: this allows to remove the custom name(MC-124327), but this won't remove the RepairCost:0 in nbt preventing to stack ~similar to when you use the trick of 'space' in the name (MC-125046/MC-181109, will be added in a future release).
