### ISSUE TITLE
Mixin crash with Immersive Portals

### ISSUE THREAD

**Issue by Xplodin** [Corail31/tombstone_lite#262]
### Minecraft Version

1.20.1

### Framework Type

Forge

### Framework Version

47.3.11

### Hybrid Server

no

### Corail Tombstone Version

8.8.4

### What happened?

Crash on boot, complains about shaders

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone on Forge/NeoForge (required)

Yes

### Occurence

occurs all the time

### Other relevant mods

Sinytra Connector, Forgified Fabric API, Corials tombstone, and Immersive Portals [Fabric]

### Log Link

https://github.com/user-attachments/files/17892843/debug.log

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
@Xplodin This fabric mod uses a redirection (for a mixin that i did a long time ago).
https://github.com/iPortalTeam/ImmersivePortalsMod/blob/1.21/src/main/java/qouteall/imm_ptl/core/mixin/client/render/shader/MixinProgram.java#L54-L61
I will change the 'require' in the next release but i'm not hurry for a mod only loadable with Sinytra Connector (personally, i had forgotten the incompatibility with this mod fixed in oct 2023).
Note that 1.20.1 is the only version not having "require = 0" (but when the mixin is skipped, this brings smoke broken with iris shaders and why it's not set in 1.20.1 to have reports of conflicting mods).
Also, if i change the 'priority', the other mod will crash due to its mixin not having require = 0.
Feel free to open an issue in the other mod. You have also the possibility to use 8.7.0 before this change.

Note that 1.21.1+ will get an update for Iris (instead of Oculus in 1.20.1) in the next release that won't need anymore the mixin.

**Comment by Corail31** [comment]
@Xplodin resolved in 8.9.0

**Comment by Xplodin** [comment]
> @Xplodin resolved in 8.9.0

awesome, goated mod and dev.
