### ISSUE TITLE
"Mysterious Gift" won't open.

### ISSUE THREAD

**Issue by GoldenFurredFox** [Corail31/tombstone_lite#268]
### Minecraft Version

1.20.1

### Framework Type

Forge

### Framework Version

47.3.10

### Corail Tombstone Version

8.8.1

### What happened?

```
This gift has appeared mysteriously and doesn't seem to want to open.
A message is written there: "Cannot be opened before December 25."
```
It's the 26th of December.
It won't open.
It's not "before December 25" anymore.

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone on Forge/NeoForge (required)

No

### Occurence

occurs all the time

### Other relevant mods

I can't reasonably test because the gift is unobtainable now.

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
The Mysterious Gift can be opened with a "soul" rounding a decorative grave by right-clicking (like others magic items).

> I can't reasonably test because the gift is unobtainable now.

The gift only appears after login if you have played at least one hour in a new game (and can also be given with command /give if you're in a Christmas period).

**Comment by GoldenFurredFox** [comment]
Ah, okay. I thought it behaved like the "Reward" item. I can't test right this second since I'm not home, but I'll still verify this regardless if you want me to before closing things.

**Comment by Corail31** [comment]
@SamHammie I already tested it to work, it was only to provide additional infos (because you won't be the only one to not know how to open this christmas gift).
I understand your logic about similar to "advancement reward" but holiday events are also to ensure that players know the base of the mod (the item tooltip after 24th is "Find a way to open the gift").
Also, note that the item will disappear if not opened after 31th december.
