### ISSUE TITLE
[1.12.2] Ankh resets when changing dims

### ISSUE THREAD

**Issue by ProsperCraft** [Corail31/tombstone_lite#27]
### Minecraft Version

1.12.2

### Forge Version

mohist-1.12.2-171-server

### Corail Tombstone Version

tombstone-4.5.0-1.12.2

### What happened?

Included video- Edit: links are not accepted (again)

This doesn't happen when teleporting with plugins to the shop dim, only when going through a portal like the nether portal or end portal, or caverns portal.

I tested in single player and it doesn't happen with only Tombstone, I have not had time to test with a dedicated server yet.

### Gametype

Dedicated Server

### Happen with only Corail Tombstone

No

### Other relevant mods

TownCraft ONE 8.12

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
@ProsperCraft I'm not sure why you open an issue knowing Mohist is not supported.
The minimal would be to test with forge and not Mohist... instead of filling a mohist version and setting the modpack as the other 5 relevant mods.
NB: i don't recommand 4.5.0 for your modpack, it's more for adventurers to test if all is working correctly as others things are going to be added in 1.12.2 before the 1.18 (the recommanded is stil 4.4.7).

**Comment by ProsperCraft** [comment]
I didn't know Mohist wasn't supported, we have been using it for many years without any problems at all.

I will downgrade to 4.4.7 next update, and disable the Ankh.

**Comment by Corail31** [comment]
@ProsperCraft if you don't make the effort to localize the trouble whatever it's one of your mods, or Mohist (that could behave differently than Forge), i can't help you (and you can consider this answer for future issues, there's a form with indication and it's not the first time that you just provide what you want to and not what is asked). For sure, Corail Tombstone is built on Forge and Mohist is not Forge. If you make the effort to localize the trouble and if it's Mohist, you could then report to them.

**Comment by ProsperCraft** [comment]
Reproduced here - https://github.com/Corail31/tombstone_lite/issues/28
