### ISSUE TITLE
invalid

### ISSUE THREAD

**Issue by KVaran** [Corail31/tombstone_lite#28]
### Minecraft Version

1.12.2

### Forge Version

14.23.5.2855

### Corail Tombstone Version

tombstone-4.5.0-1.12.2

### What happened?

Expected result: When praying, Ankh of Pray should keep cooldown when traveling through nether/end portals

Actual result: Ankh of Pray resets cooldown when entering a portal, trivializing knowledge of death level gain

Steps to reproduce:
Pray normally, walk through portal, return, pray immediately without the cooldown.

### Gametype

Singleplayer

### Happen with only Corail Tombstone

Yes

### Other relevant mods

- None

### Valid Launcher

- [X] Yes

**Comment by KVaran** [comment]
So it's intended then? Okay, kinda makes the mod useless.

**Comment by Corail31** [comment]
@KVaran if you don't fill correctly the issue with the required infos, don't be surprised to get such answer, it was tested to work properly on server and singleplayer. Also note that Prosper said it was working with only Tombstone in singleplayer but he wasn't able to make the server test. If you're also using Mohist that is known to have trouble on server, it's not something that can be solved in mods, it's up to Mohist to behave like Forge.

**Comment by KVaran** [comment]
And yet, this wasn't tested on a server or with whatever Mohist is. This is in singleplayer, not on a server, and it clearly says so in the issue description.

**Comment by Corail31** [comment]
What you didn't read into this ? "if you don't fill correctly the issue with the required infos".
If the informations are incorrect, you won't get an correct answer, because theses infos help to answer you (and to help you even if you add silly comments like this "So it's intended then? Okay, kinda makes the mod useless.")
It was tested "by me" on server and singleplayer (and even with end and credit).
Trolls are really not welcome in this place, whatever it's just your lazyness to post/test the mods to make this happening (behind your freshly created github account).
NB: if others trolls happen, only existing accounts with a certain time will be accepted for issues.
