### ISSUE TITLE
Issue with Enigmatic Legacy Compatibility

### ISSUE THREAD

**Issue by Darkmega18** [Corail31/tombstone_lite#31]
### Minecraft Version

1.16.5

### Forge Version

36.2.8

### Corail Tombstone Version

6.6.1-1.16.5

### What happened?

Currently, I have tombstone set up so that I don't use tombstones for death item storage.
I instead use **Enigmatic Legacy's own enigmatic amulet** that you spawn with, which contains your items on death in an invulnerable capsule at your location of death provided you have it on so that item protection requires holding onto the charm as it's also central to my modpack's story of sorts.

_This was working until recently when I noticed you added compatibility for enigmatic legacy's cursed ring and the aforementioned amulet._

Instead what happens is that now when I die the enigmatic legacy amulet fails to work and my items explode everywhere and when I return to my death pile the amulet is nowhere to be found: it is just deleted.
**This is with Tombstones configured to NOT handle death at all.** 

I've mostly got it for the grave magic, phylacteries and other features like knowledge of death etc.

### Log Link

There isn't a log. it's not a crash.

### Gametype

Singleplayer

### Happen with only Corail Tombstone

No

### Other relevant mods

Enigmatic Legacy

### Valid Launcher

- [x] Yes

**Comment by Corail31** [comment]
In case, you haven't noticed: tombstone is a grave mod, and any mod handling drops at a wrong stage make it incompatible, or require some compats.
So, the first step of this compat was to fix this (and also prevents the error of this mod when teleporting to the death position).
The compat have been done with the intention of Tombstone being activated and players having the choice if they want to use the grave or the amulet (what this mod doesn't propose on its own).
Any way, others compats will come with this mod as i discussed with the modder yesterday (phantom active on players with cursed ring and to not lose the amulet until the next grave when players cheat death).
But, it's not for now but when i'll have contents to publish on 1.16.5, you have perhaps a story in your modpack but the role of this mod is to handle the drops (and make them safe).
NB: nothing prevents you to stay on your previous version as this first compat was for those using Tombstone "normally", and 1.18 is nearly there. Your amulet will be retrieved the next time you die with tombstone enabled.

**Comment by Darkmega18** [comment]
![image](https://user-images.githubusercontent.com/8104689/143479206-9f5259cb-6e45-432e-b809-7e0e34253fb1.png)
seems I found this posts of yours. Switching that setting off and now the amulet is working and not being deleted. So seems it was a bit of a situational false alarm.

> In case, you haven't noticed: tombstone is a grave mod

I do get this. But lets just say sometimes it does it's job too well. 

My reasoning being that I wanted the items to be slightly less safe, but still safe from the usual despawning and stuff but also be collectible by other players without the extra steps of gravestone's grave raiding and such.

Theres also the return key to consider which can get you back instantly but deprives people of the "fun" of having a contingency plan to potentially find their way back to collect their gear and such before ghostly shape times out and they have a bad time which was part of my consideration. 
But all your other features do have weight to add to a magical side of the pack also so it was kept in for these other cool and useful additions. 
For example I use bait and diversion frequently for mob aggro manipulation in origins, and it has applications in stealth gameplay provided by another mod. 
While ankh is a very potent zombie villager saver (or zombie villager maker, if you're evil!) and tablets are good for instantly going for exploration or cooperative assistance recalls in servers.
The Soul Receptacle also being the most potent death protection mechanic based item that I know of. So it does have some very physically useful mechanics, even without it's intended primary use.

anyways, sorry for bothering you.

**Comment by Corail31** [comment]
@Darkmega18 The recommanded version is still 6.5.5, it's rare when i write a code in one time, generally i always change things a while after.
There's anyway a small trouble with this compat until a future release: it considers the server config about death handling enabled (what you noticed and why you got your drops on the ground when you disables it), and if a player cheats death (with something done in the death event), the amulet will disappear until the player dies. I have also my wrapper of PhantomSpawner to adapt as it prevents the cursed ring to force the spawn on them.
It's minor details like changing the place of my hook and checking the config, but it's just not for now, i wanted to add something for Christmas but with 1.18 in the way... ^^
Edit: about the phantom, the roll should be done twice, about Christmas, it is already late to publish in time.
Disabling the death handling on the server is only provided because there're some incompatible mods (and most of them don't make efforts to be), but there's no support when it's done as they shouldn't be launched together. (it is not the case of Enigmatic Legacy as i'm on the way to add this compat, but it wasn't before this compat)
If someone reports something to fix in 1.16.5, the compat will be improved on the same time. (and i recommand to anyone wanting fixes in 1.16.5 & 1.17.1 to report them before 1.18)
Edit2: i sent you a version if you want to check if all is ok.

**Comment by Darkmega18** [comment]
Huh, I thought phantoms were just handled normally? since the cursed ring stops you sleeping, so sooner or later the phantoms will just start showing up, even with your knowledge of death extending the time before they can appear.

We (myself and friends on server) usually get around it by drinking dandelion cola from mystical world which resets the timer on it. (or meditating with Project War Dance. which now does similar)

But I see. I'll continue to monitor if the amulet remains fine and if it does get too dicey and starts going poof again I'll backport then and can always get it back with a player inventory backup...

> i wanted to add something for Christmas but with 1.18 in the way... ^^

Hmm... Santa Grave guardian? Presents full of lollipops? the ghosts of christmas past present and future? xD But yeah, the public will probably be demanding their updates for 1.18. :V
