### ISSUE TITLE
I lost my stuff and have a .save file, (the issue is not from the mod)

### ISSUE THREAD

**Issue by ElectroGehirn** [Corail31/tombstone_lite#34]
### Minecraft Version

1.17.1

### Forge Version

37.0.97

### Corail Tombstone Version

7.2.5

### What happened?

I lost my stuff and have a .save file, how i can get my stuff back with the file?

### Gametype

Dedicated Server

### Happen with only Corail Tombstone

Yes

### Valid Launcher

- [x] Yes

**Comment by Corail31** [comment]
Hi, "questions" are on curseForge like it's explained in the form that you filled and where even the page lists the available commands (/tbrecovery).
I would be curious how you succeed to lose your stuff, graves are not breakeable, it's probably related to one of your others mods unlike your title seems to say. If you got an error, why there's no debug log with your issue ?
Your issue is invalid ("Happen with only Corail Tombstone" -> Yes)

**Comment by ElectroGehirn** [comment]
it was a server crash, and i had my grave and at the monent who i grab my stuff the server is crashed and the grave was gone with my stuff, but i found a save file with my stuff

**Comment by ElectroGehirn** [comment]
![image](https://user-images.githubusercontent.com/79157955/145082787-0e5bfaff-14ce-4065-995a-1f0adb357c34.png)
Oh fck, i I have misspellt, its meaning (Not from the mod
)

**Comment by Corail31** [comment]
@ElectroGehirn if you find the debug log about this crash, i could look at it. But consider to ask on curseforge when you have only a question, i really want a separation to "preserve my hobby time".
NB: I often do mistakes in english too (i realized recently that i used "annoy" instead of "bother" due to the proximity with the french verb "ennuyer" ^^).
Edit: i'm not specially informed about modpack (i'm not a player), but if you're in 1.17.1+, it's recommanded to stay around 6/7 gb ram whatever the amount of mods. If you're in 1.15.2, i recommand you to update to an upper minecraft version.
Don't manipulate the file yourself, just use the command /tbrecovery load_player [player] [save] with the permission for your server and use "tab" for the autocompletion.

**Comment by ElectroGehirn** [comment]
i can give u that but you cant make something with it,wile its only a server crash wile i was over 60000 ticks or something, my server hoster is only sh*t, the server has 5gb of ram and a AMD Ryzen 5 3600, but that good for a server idk how this happend, but its not youre mod, and yes its a question, i dont know what i can do with the .save file with my stuff info in there but what i can say u what to, youre mod is the best of all grave stone mods that i know, i had not at any time lost my ites or a bug with youre mod, idk how youre mod is sooo good and bug free, but i give u a big like for that good mod, i had make a yt video for youre mod after a year xD, but it think now the video is cringe xd, but anytime i make a new one, and btw in the video i said, dont use any grave mod, use corail, that is the best you can choice xdd
and realy thank you for this, i am at 1.15 with youre mod
