### ISSUE TITLE
Crash due to grave smoke

### ISSUE THREAD

**Issue by Potatomonium** [Corail31/tombstone_lite#39]
### Minecraft Version

1.18

### Forge Version

39.0.55

### Corail Tombstone Version

7.3.6.1.18

### What happened?

Client crashes on launch due to "Error: java.lang.IllegalStateException: Failed to load description for particle tombstone:grave_smoke"

### Log Link

https://pastebin.com/73DkgFud - with Resource packs
https://pastebin.com/6iAJLQcR - Without Resource packs
### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone

No

### Other relevant mods

I started adding mods in a few at a time and I found that I still had the Tombstone version 7.3.5.jar still in my list. I use the CurseForge launcher and it seems that it's not deleting old versions of mods when updating them through the launcher as there have been other mods that had old versions remain in my mod folder.

I'll close the issue now

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
@Potatomonium for info, the particleType "grave_smoke" is removed in 7.3.6 and replace with "smoke_cloud".
If you want support, you have to provide the debug log (and not a half log), make the test with only Tombstone, and correctly fill the informations (like if you were joining a server, and that you were on a hacked launcher ~uuid) because your explanation has no logic.
Edit: someone reported the same trouble with the launcher keeping old versions, so i suppose it's normal.
