### ISSUE TITLE
Crash when migration in MineColonies Official 1.18.1 - 4 by using Forge 39.0.57+

### ISSUE THREAD

**Issue by attilavv** [Corail31/tombstone_lite#41]
### Minecraft Version

1.18

### Forge Version

forge-1.18.1-39.0.59

### Corail Tombstone Version

tombstone-7.3.6-1.18

### What happened?

Client crash when render a guardian.

### Log Link

https://github.com/attilavv/MineColonies-Official-1.18.1---4/blob/main/crash-2022-01-27_10.12.48-client.txt

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone

No

### Other relevant mods

MineColonies Official modpack + 54 mods

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
You bypassed the test asked in this issue template (the support is not for modpacks except if you make the sort yourself in your others mods to localize the mod making a trouble with armorModel). You also provided a half log (it's debug log that is requested in case of crash).
-> closed

**Comment by Corail31** [comment]
@attilavv by looking Forge, they added a [breaking change](https://github.com/MinecraftForge/MinecraftForge/commit/fd522d38b00f6b7e8021fa75634a9aec74c5c301#diff-f59444185dd810a2fc6b27b66a93696e1830d857f0cd6db1142aff8f6e4b60b6L7-R7) 6 days ago related to that method, just stay on forge version 39.0.48- (or 39.0.55/39.0.56 because the versions of Forge between are broken).
A version will be published soon to take in account that change.
Personally, i wouldn't recommand to update forge to newer versions until the RB ;)
