### ISSUE TITLE
Minecraft Crashing by not using the required forge version

### ISSUE THREAD

**Issue by HelixCreations** [Corail31/tombstone_lite#42]
### Minecraft Version

1.18

### Forge Version

39.0.8

### Corail Tombstone Version

tombstone-7.3.7-1.18

### What happened?

Upon starting up Minecraft it throws an error.

### Log Link

https://pastebin.com/wPQ4yB8a

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone

No

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
The version requires Forge 39.0.17+ (it's on the changelog)
Forge broke all custom particleRenderType since 39.0.17 (they all render in the same renderType) and why there's a fix about it to allow me to apply improvements without a crash of the code if they were running in the same renderType.
NB: the previous version has no requirement (and i'll look to lower the forge version in the next release).
