### ISSUE TITLE
Harder Enchanted Grave's Key Recipe

### ISSUE THREAD

**Issue by mrdeadlocked** [Corail31/tombstone_lite#54]
Could we get a config option for a harder graves key recipe? or the ability to change the recipe in some way. It doesn't seem like the key recipe can be changed with the tweaker mods due to NBT/data that is stored on the key.

**Comment by Corail31** [comment]
@mrdeadlocked I don't play enough to see what others mods propose to change your recipes (when an ingredient is the result), so i put the recipe with the key in the api, to allow you to replace it with a new one. Would it be enough?
NB : the result of the key is the copy of the key ingredient with a value in nbt "enchant" to true.

**Comment by mrdeadlocked** [comment]
Ya. the ability to adjust the key recipe ourselves would be great! thanks.

**Comment by mrdeadlocked** [comment]
How would one go about using the API? Normally we are used to contentweaker/minetweaker to change recipes. Sorry for the added questions. :-)

**Comment by Corail31** [comment]
So, ContentTweaker... mineTweaker are mods that are doing things for you with limitation probably (i don't play so i don't specially know how to use them), and i don't think it's to me to provide help in theses mods to be able to use an "upgrade recipe".
So, to use an api, it requires to use java code from another mod to register the new recipe?
That's why i said you first i don't know how others mods do for this in general, and i don't think it's to me to provide some support to craftTweaker?

**Comment by mrdeadlocked** [comment]
I don't know what it would take to have a mod support content tweaker but I know a lot of mods do.
https://crafttweaker.readthedocs.io/en/latest/#

It used a json file to make a recipe for the item that is loaded on startup. Example recipe from content tweaker is below.

# Wood Casing
	recipes.remove(<actuallyadditions:block_misc:4>);
	recipes.addShapedMirrored("Wood Casing", 
	<actuallyadditions:block_misc:4> * 2, 
	[[<ore:plankTreatedWood>, <forestry:oak_stick>, <ore:plankTreatedWood>],
	[<forestry:oak_stick>, <ore:logWood>, <forestry:oak_stick>], 
	[<ore:plankTreatedWood>, <forestry:oak_stick>, <ore:plankTreatedWood>]]);

**Comment by Corail31** [comment]
I'm ok with you but your example seems to be done for normal recipe : for the key, the result is one of the ingredient and need to be this exact itemstack to keep the location of the grave.

**Comment by dierke9** [comment]
You say that english is not your first language, and i see on your github profile that you are from belgium.
Are you from the Flemish side? If that is the case, and if you have Discord could you add me so that we can take alook and discuss this please?

**Comment by Corail31** [comment]
I speak french, and for discord, np :)

**Comment by dierke9** [comment]
Ah damn wrong side of Belgium, for me atleast and my French aint that good :(

**Comment by mrdeadlocked** [comment]
Would it be possible to just make it a config entry that could be changed to have the recipe swap 'enderpearl' for whatever item is in the config?

**Comment by Corail31** [comment]
Did you ask for advices on the CraftTweaker discord first ?  (as it's what you use and is your really trouble, as nearly this issue should be on their mod, as the other way to change the recipe is to use the api and java...)
Your objective is to make the recipe more complex, so not just to edit one unique ingredient required, so it would require more than one config option to describe a recipe with item with meta & nbt.
So no, because of this and because i don't want to get surprise of recipe not correctly sync.

**Comment by mrdeadlocked** [comment]
I did not ask for craft tweaker discord. It would work just as well for server/modpack makers to have a config option to decide what item combines with the key instead of the ender pearl. This item could then be made/created however the modpack/server would want (or from any other mod) recipe wouldn't matter then.

**Comment by Corail31** [comment]
@mrdeadlocked i changed the oredict to be "ingredientEnchantedGraveKey" instead of "enderpearl", so you can now tweak this oredict to change the ingredient ;)
