### ISSUE TITLE
Error in logs - DeathEvents

### ISSUE THREAD

**Issue by Maypul** [Corail31/tombstone_lite#54]
### Minecraft Version

1.18.2

### Forge Version

40.1.19 (also tested on 40.1.0)

### Corail Tombstone Version

7.4.5 (latest at the moment)

### What happened?

Copied the mod to the mod folders, started up the game, checked the logs.
From what I have remember this was not happening in some previous versions, I have updated few mods, checked logs and noticed additional errors, tested only this mod on frest MC installation and noticed it's still logging it.

Full log attached below, entries I am talking about are;
[14:39:59] [main/WARN] [mixin/]: Error loading class: de/maxhenkel/gravestone/events/DeathEvents (java.lang.ClassNotFoundException: de.maxhenkel.gravestone.events.DeathEvents)
[14:39:59] [main/WARN] [mixin/]: Error loading class: de/maxhenkel/corpse/events/DeathEvents (java.lang.ClassNotFoundException: de.maxhenkel.corpse.events.DeathEvents)

### Log Link

https://pastebin.com/XcyQubSd

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone

Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
It's normal log when using @Pseudo (virtual target) with mixin.
It allows minimal compatibilities with thoses mods when present.
If anyone knows of a way to not show this log when using this annotation, i would appreciate it ;)
NB: it's because i use 'targets' and not 'value' in the mixin annotation, so it warns.
