### ISSUE TITLE
mixin crash

### ISSUE THREAD

**Issue by Tyrius1** [Corail31/tombstone_lite#55]
### Minecraft Version

1.18.2

### Forge Version

40.1.19

### Corail Tombstone Version

tombstone-7.4.5-1.18.2

### What happened?

When combined with AoA it crashes on launch.
AoA offered this insight:
"add the requires section to their mixin and set it to 0, so that it can failsoft"

### Log Link

https://pastebin.com/30UAQ76j

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone

No

### Other relevant mods

https://www.curseforge.com/minecraft/mc-mods/advent-of-ascension-nevermine

### Valid Launcher

- [X] Yes

**Comment by Tslat** [comment]
This will eventually be fixed once we finally get the forge guys to push through this PR:
https://github.com/MinecraftForge/MinecraftForge/pull/8478

But for now, it's just the reality of what we need to do to prevent crashes

Pretty easy fix, can basically just throw requires = 0 in your mixin so that it overrides the default value of 1 from your mixins.json
This allows the mixin to silently fail if it doesn't find its matching target (which happens when another mod patches the same thing you're patching, but does it before you)

**Comment by Corail31** [comment]
Hi, it's similar to the compat with Pehkui and the method pick in GameRenderer.
It's not a bad idea to set the param 'require' for fail soft and might be a reason to re-add it in 1.16.5.
Edit: you can probably change the priority of your mixin to be after others mods as a provisory solution (the 9d thing).

**Comment by Tslat** [comment]
It'll be a common crash with a whole bunch of mods, in both 1.18 and 1.16.5 (and a bunch of other versions)
No-one seems to know/think to override the require to failsoft on this thing, so there's a whole bunch mods out there (including this one) that is crashing because of this

Pehkui is one of them IIRC yeah
