### ISSUE TITLE
[Suggestion] Giving graves spawning ability (configurable). 2 totems. And a mob.

### ISSUE THREAD

**Issue by Thunder-Nova** [Corail31/tombstone_lite#58]
So I've looking into this mod and pretty much love it in and out.

So even if refused, I am still happy about this mod.

To the point, adding a spawn system to graves. But to make it less annoying, there are 2 ways to get those graves to spawn:

Natural spawn (Graveyards generation if it's good), and a "Cursed" totem used on any grave, even player graves for special zombified mobs. If a player dies whilst holding a "Cursed" Totem, their grave will instantly turn into a cursed "player named" grave destroying the totem at the same time.

The graves can't be dropped, meaning break it, it vanishes. They also won't spawn spirits, except with a "Blessing" Totem. The "Blessing" totem acts as protection, giving the grave an obsidian level of mining required to break the grave.

If possible, for the Zombified mobs, you can simply make a green hue of a player skin (generated by the player grave). This is a single spawn zombie that will destroy the grave but will hold all the items, including the armor, and best weapon.

This gives pvp a more risk and take situation. Requiring the pvp player to bring at least a diamond pickaxe. This should also be configurable, so servers or modpacks can add mining level requirement.

**Comment by Corail31** [comment]
Hi Thunder-Nova,
I try to keep Tombstone as a grave mod in priority and relatively small, so the mod doesn't generate things, or add entities.
But, an addon is planned for this kind of contents (but no date honestly), and some parts are already done since a long time, like some seals applicable on graves (more related to villages and will fit nice with 1.14), some random graves with others behaviors and encounters (which is not so far from your suggestion).
So, i can just say you : wait and see but it's not for now :)

**Comment by Thunder-Nova** [comment]
No problèmo ;)
