### ISSUE TITLE
Mercy effect (or maybe any effect that divide something by zero

### ISSUE THREAD

**Issue by ghost** [Corail31/tombstone_lite#66]
### Minecraft Version

1.19

### Forge Version

41.0.98

### Corail Tombstone Version

8.0.3

### What happened?

so i was playing Minecraft, i found a papyrus of Mercy, i used and it was normal, but then i got attacked by zombies, and i was run away, and it stopped and crashed 
[crash-2022-07-15_23.32.26-server.txt](https://github.com/Corail31/tombstone_lite/files/9123945/crash-2022-07-15_23.32.26-server.txt)

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone

No

### Other relevant mods

none

### Valid Launcher

- [x] Yes

**Comment by Corail31** [comment]
Hi and thanks you for bringing this problem here.
If i published this version, it's more because forge did some breaking changes, not because my changes were ready.
As most things in Tombstone, you can disable them in config.
NB: it's a neutral effect, so you won't receive it with pray, lollipops, and so on.

**Comment by ghost** [comment]
or i could just disabled that mod until its fixed again
because, what i really like to do with this mod is disenchanting books or items 
and i dont know if i could disable in config
im really noob at editing stuff at config
i might gonna make mistake
