### ISSUE TITLE
I dont have a grave when i die

### ISSUE THREAD

**Issue by RMML27** [Corail31/tombstone_lite#68]
### Minecraft Version

1.18.2

### Forge Version

40.1.54

### Corail Tombstone Version

7.4.10

### What happened?

I don't know why but it is activated so that I don't have a grave when I die and I don't know how to remove it.

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (this test is required)

Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
This section is for real issues.
Delete your configs on the server (and also on your client due to "player preferences"). If the server is not yours, it's how that server configured it. Also, don't use Forge "alternatives" (magma, and so on).
If you have an error in your logs when you die, it would be better to include this log in your message.
Tombstone always provides a message to a player that dies (and also when it is canceled in the logs).
NB: Sorry in advance how issues are handled, but it's related to the time that i can accord to mc.

**Comment by OcrSu** [comment]
I had the same problem.
But I think it's an incompatibility between mods
Log:[Server thread/WARN] [tombstone/]: The drop event of the player OcrSu was canceled by another mod

**Comment by Corail31** [comment]
@OcrSu It's a different thing, your message is more a notification when a mod choose to handle the death.
If you have some mod behaviors on death that don't work well with tombstone, you can open a new issue with the details and i could probably make some compatibility.
The report here is about something happening with only Corail Tombstone (or the report is invalid due to wrong infos as i checked it to work properly).

**Comment by OcrSu** [comment]
> @OcrSu It's a different thing, your message is more a notification when a mod choose to handle the death. If you have some mod behaviors on death that don't work well with tombstone, you can open a new issue with the details and i could probably make some compatibility. The report here is about something happening with only Corail Tombstone (or the report is invalid due to wrong infos as i checked it to work properly).

I'm checking out which mod is causing the bug.
This may take some time, I have 220 mods in my modpack
When I find it, I will open a new issue

**Comment by OcrSu** [comment]
> > @OcrSu It's a different thing, your message is more a notification when a mod choose to handle the death. If you have some mod behaviors on death that don't work well with tombstone, you can open a new issue with the details and i could probably make some compatibility. The report here is about something happening with only Corail Tombstone (or the report is invalid due to wrong infos as i checked it to work properly).
> 
> I'm checking out which mod is causing the bug. This may take some time, I have 220 mods in my modpack When I find it, I will open a new issue

It has been solved, it was my mistake.
I added the Inventory Home mod before I added the corail tombstone mod, but I forgot about it.
Now I found it. Sorry for the disturbance.

**Comment by Corail31** [comment]
@OcrSu That's fine, in general, what players bring me as trouble help me later to explain the possible problems ;)
