### ISSUE TITLE
Key wont work

### ISSUE THREAD

**Issue by WolfSpeedXD** [Corail31/tombstone_lite#74]
### Minecraft Version

1.12.2

### Forge Version

14.23.5.2859

### Corail Tombstone Version

4.4.7

### What happened?

I just created a new world with the same mods that i always use, but this time i made a plain world. This is my first bug report sorry if its wrong but its pretty simple, when i die i go to my grave as usual but key and shifting dont work with the grave

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (this test is required)

Yes

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
It's not about to be used or not but to be able to read a template.
Your infos are wrong because it's about some mods that you use in a plain world, and you check it's happening with only Tombstone (and the key is not needed to open a grave so i would even suppose it's a fake, "key and shifting" has no mean to me).
You're also not on latest.
