### ISSUE TITLE
Stuck outside world border

### ISSUE THREAD

**Issue by TheTechPny** [Corail31/tombstone_lite#8]
### Minecraft Version

1.16.5

### Forge Version

36.2.2

### Corail Tombstone Version

tombstone-1.16-6.4.7

### What happened?

Whenever a player enters a new dimension but enters from outside the world border, they get stuck and can't move or get out. The problem occurs when the player has not touched knowledge of death
No logs or errors with this one

Example
Player overworld cords are 82k, 82k and they teleport to a dimension with border of 20k then they get stuck like the screenshots. 

These are from the players perspective
*****_(edit: image are not accepted and is not the informations required!)_

### Gametype

Dedicated Server

### Tested with only Corail Tombstone

- [ ] Yes

**Comment by Corail31** [comment]
"If you want some helps, you need to fill the relevant informations, and theses informations include to test the mod with only Corail Tombstone or to find the related mods that make your trouble happening.
Without theses informations, don't open issues as you won't get any answer as any mod can break your setup."
NB: if people are not able to fill this form, the issues will be definitively closed.
Also, it's not because Corail Tombstone can save players from dying outside World Border (and this option exists since ages) that it would be related to your issue that is only because you put multiple mods together and hope them to work without test(and think that modders will do the job for you, but it's not)
