### ISSUE TITLE
Unable to use Tombstone commands on command block

### ISSUE THREAD

**Issue by carlosr9** [Corail31/tombstone_lite#85]
### Minecraft Version

1.18.2

### Forge Version

40.1.76

### Corail Tombstone Version

7.4.9

### What happened?

_I cannot use tombstone command on command block. At first, I tried to use /tbrestoreinventory, but seeing that it did not work I tried with the rest of the commands. None worked in the command block. 
Is this a bug or something wanted? It would be really helpful to be able to use the commands in the command block._

Solution reached: These commands just require a player to execute them. Using /execute as [player] run [tb command] it will perfectly worked. 

Sorry for the inconvenience.

PS: They work perfectly in the command bar.

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Commands use permission level 2  so, i suppose the problem is something else in your setup.
I'm not informed enough about command blocks as i don't play but i'm going to do tests about it ;)

**Comment by Corail31** [comment]
The command /tbrestoreinventory has a parameter for the player.
The error occurred when this parameter was omitted due to a missing return and check for IllegalArgumentException while getting a default player (the one using the command). It also affected the command /tbshowlastgrave.
NB: in short, /tbrestoreinventory returned an error with no player param and wasn't working to target an other player. It exists since 6.4.0 for 1.16.5
