### ISSUE TITLE
Tombstone not generated after death/disconnect [PlayerRevive]

### ISSUE THREAD

**Issue by SrRapero720** [Corail31/tombstone_lite#94]
### Minecraft Version

1.18.2

### Forge Version

40.1.80

### Corail Tombstone Version

tombstone-7.5.3-1.18.2.jar

### What happened?

Acttually i have very low information (excepting log events)
When a playera die and lost connection (timeout) death event are discarted and ítems get lost.

Player dies many times and death event Is handled by PlayerRevive, after surrender everythint Is ok

But if player dies and server disconnect player by timeout PlayerRevive or Tombstone no handle nothing AND after reconect no ítems, no key and no backpacks.

ITS rare because a minory of players gets a timeout disconnect (by internet down)

No Hybrids, Cursedforge modpack

Thats a problem reported by a user from my server.
LOGS: 
[2022-10-09-3.log](https://github.com/Corail31/tombstone_lite/files/9745877/2022-10-09-3.log)

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs rarely

### Other relevant mods

PlayerRevive, TravelersBackpack, FTB (all)

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
@SrRapero720 As far as i know, PlayerRevive kills the player on a disconnect bringing a notable bug that is reported by others mods:
https://github.com/CreativeMD/PlayerRevive/issues/92
https://github.com/CreativeMD/PlayerRevive/issues/29
https://github.com/CreativeMD/PlayerRevive/issues/68
https://github.com/VazkiiMods/Quark/issues/3849
I suppose the modder has to fix it on its side, so i don't know why he closes the issues related to it.
NB: your log is not helpful, it doesn't even show your mod list (and it's better to test your issue with a limited number of mods)

**Comment by SrRapero720** [comment]
Sorry isn't posible document a problem if is not a crash (so logs is the only notice thing)
Actually i see its a problem of PlayerRevive. The most notable same thing in the issue is all are a server. So maybe the "solution" is add a delay/handler for player fullconnect.

**Comment by Corail31** [comment]
@SrRapero720 as i mentioned above, you have to reduce your mod list to a minimal list (what is asked by the issue template, and that you're not doing).
The modder of PlayerRevive kills the player to avoid players to abuse to disconnect to wait for players to "revive" them.
Then, if the drop event is not fired or if the captured drops have been overwritten, it's normal to have no grave.
There's nothing to fix on my side, open an issue on PlayerRevive github.
You can use the command /tbrecovery load_player <player> <save>.

**Comment by SrRapero720** [comment]
tbrecovery no works, no tomb generated and no key (so only recover).
I still checked most of the mods and except for the FTB none interact with the death events like the "tombs" or the "revive" so I feel that it is a bit hasty to declare it invalid (but it doesn't matter anymore).

Well, thanks for confirming that the problem may be PlayerRevive, I will report the problem to the creator.

**Comment by Corail31** [comment]
@SrRapero720 "I feel that it is a bit hasty to declare it invalid (but it doesn't matter anymore)." -> feel free to think what you want, a grave appears if the 'livingDrop event' is fired, there's nothing to look anymore (even more if you're not respecting the template for issues).
PlayerRevive handles its code 'around the death event' before the 'drop event' and what happens there is related to your others mods.
PlayerRevive can have incompatibilities with FirstAid, Mohist, Magma, Vampirism (and features reviving during the 'death event' like twilight forest charms).
I already sent a message to the modder of PlayerRevive some months ago to take care how he kills the player because the issue  looked similar to the old bug with sacrificial dagger in Blood Magic and if i remember well i made the tests by disconnecting a player on a server but there was no bug with only Corail Tombstone & PlayerRevive.
I also don't think he really needs to kill the player on disconnect to prevent abuses, there're probably others solutions (and is there really a need to prevent players to abuse by disconnecting ? there're not playing while waiting for a player and it encourages mutual aid).
The fact that you didn't reduce your mod list, prevents to have a readable server log showing when a player died.
I may be closing the issue but I hope you understand that I am trying to bring you the information that could help.
NB: tbrecovery  works but it's not to make a grave to appear but to restore your inventory before your death and your position (and why you need to choose the adequate "save" with the command parameters and autocompletion).
