### ISSUE TITLE
Lolli's color change not lplaying well with sophistacated backpack mod

### ISSUE THREAD

**Issue by deadlywolf301** [Corail31/tombstone_lite#98]
### Minecraft Version

1.16.5

### Forge Version

36.2.39

### Corail Tombstone Version

6.8.4

### What happened?

so when using an auto pickup upgrade in the backpack when ever you loot more then one lolli of the same color there's a chance that itll crash due to the lolli maybe changing color when picked up in to a backpack. doctor mage on discord had this to show and i quote: yeah just recreated it solo with corail tombstone (ftb libary but that was for looting 100 sword)
[crash-2022-10-22_11.00.29-server.txt](https://github.com/Corail31/tombstone_lite/files/9844074/crash-2022-10-22_11.00.29-server.txt)
[debug.log](https://github.com/Corail31/tombstone_lite/files/9844075/debug.log)
[latest.log](https://github.com/Corail31/tombstone_lite/files/9844076/latest.log)

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Other relevant mods

sophisticated backpacks latest version

### Log Link

https://pastebin.com/eh7KtN58

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
"looks like ill have to try a different grave stone mod didnt realise the author was a dick"
-> Thanks for spamming my repo (you're now blocked).
I have no time to waste with childish and insulting children as if they had the right to claim anything
https://github.com/Corail31/tombstone_lite/issues/97
Lollipops are the same since the start of 1.16.5, they didn't get changed and are available in the creative inventory all the year.
The only peculiarity is they're colored from their color in nbt. You can try with Forge 36.2.14 to compare if it's related to the lazy loading of capabilities.
I said you that graves have no trouble to store lollipops, and it's related to the messy code in SophisticalBackpacks.
Seriously what is this code for a backpack, there's nothing else to discuss about it (and this class doesn't exist in above versions):
https://github.com/P3pp3rF1y/SophisticatedBackpacks/blob/1.16.x/src/main/java/net/p3pp3rf1y/sophisticatedbackpacks/util/InventoryHandlerSlotTracker.java
If they get a null pointer, it's related to what is done in it and they could catch it as they know what they do.
I'll have look to init the nbt differently in lollipops.
